// Curated from public professional sources; hiring evidence is separate from fit.
export const reviewedAt = '2026-10-07';
const rechecked = new Set(['ozlem-kalinli', 'koki-nagano', 'jonathan-petit', 'deepak-chandran', 'desh-raj', 'sangho-lee', 'umar-iqbal', 'marco-pavone']);
export const profile = 'https://jrohsc.github.io/';
export const papers = {
  duplex: { label: 'DuplexJail · preprint', url: 'https://arxiv.org/abs/2609.09420' },
  audio: { label: 'Audio jailbreaking · COLM 2025', url: 'https://arxiv.org/abs/2504.01094' },
  finetune: { label: 'Audio fine-tuning safety · preprint', url: 'https://arxiv.org/abs/2604.16659' },
  codec: { label: 'CodecAttack · preprint', url: 'https://arxiv.org/abs/2605.20519' },
  bias: { label: 'B² · USENIX Security 2025', url: 'https://arxiv.org/abs/2406.15213' },
  confetti: { label: 'Bob’s Confetti · preprint', url: 'https://arxiv.org/abs/2507.17937' },
  spill: { label: 'SPILLage · preprint', url: 'https://arxiv.org/abs/2602.13516' },
};
const source = (label, url, kind = 'research') => ({ label, url, kind });
const amri = 'https://research.nvidia.com/labs/amri/post/internships_for_summer_2027/';
const msr = 'https://apply.careers.microsoft.com/careers/job/1970393557022480';
const dair = 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/PhD-Research-Intern--Learning-Embodied-Skills-from-Human-Data---2027_JR2025405';
const aspire = 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/PhD-Research-Intern--Autonomous-Systems-and-Physical-AI-Research---2027_JR2024171';
const signature = '\n\nBest,\nJaechul Roh\nPhD candidate, UMass Amherst\nhttps://jrohsc.github.io/';
const unknown = '2027 공고 미확인';

export const contacts = [
  {
    id: 'ozlem-kalinli', name: 'Ozlem Kalinli', first: 'Ozlem', company: 'Meta', team: 'Speech / realtime voice · MSL',
    approach: 'research', fit: 'core', location: '미국 팀 배치·근무지 문의', tags: ['Full-duplex', 'Speech', 'Tool use'],
    hiring: { kind: 'unannounced', label: unknown, note: '최근 Muse Realtime Voice·ASR 글은 연구 접점의 근거입니다. 2027 인턴 모집 공고로 해석하지 않습니다.' },
    why: '진행 중인 대화, 실시간 끼어들기, 백그라운드 작업을 함께 다룬다는 점이 현재 연구 질문과 매우 가깝습니다.',
    advice: '부담 낮게, 질문은 명확하게. 최근 글의 구체적인 접점 → Dolby 경험 → 2027 미국 PhD 인턴을 고려하는지 한 가지 질문.',
    links: { linkedin: 'https://www.linkedin.com/in/ozlem-kalinli-2b44097' },
    sources: [source('Muse Realtime Voice · 최근 본인 글', 'https://www.linkedin.com/posts/ozlem-kalinli-2b44097_meta-connect-2026-news-conference-updates-activity-7508748420912881665-4Iy7'), source('Muse Voice Transcribe · ASR / diarization', 'https://www.linkedin.com/posts/ozlem-kalinli-2b44097_introducing-muse-voice-transcribe-activity-7500624841058914305-8tj4')],
    papers: ['duplex', 'audio'], subject: '2027 PhD internship inquiry — full-duplex voice agents',
    email: `Hi Ozlem,\n\nYour recent post on Muse Realtime Voice caught my attention, particularly handling interruptions while work continues in the background. I’m a CS PhD candidate at UMass Amherst with Amir Houmansadr. During my 2026 Dolby research internship, I worked on full-duplex speech safety, including DuplexJail.\n\nI’m now studying how revisions to speaker or authorization evidence should invalidate pending tool actions in an ongoing voice interaction. I’m also interested in broader questions of robust speech interaction and evaluation.\n\nWould your team be considering US-based PhD research interns for summer 2027 working on related problems? I’d be happy to share my CV and a short research summary if useful.${signature}`,
    dm: 'Hi Ozlem — your Muse Realtime Voice post on interruptions and background tasks closely connects to my work. I’m a UMass Amherst PhD candidate and recently worked on full-duplex speech safety at Dolby (DuplexJail). I’m now studying speaker authorization for pending voice-agent actions. Would your team be considering US PhD research interns for summer 2027 in this area? https://jrohsc.github.io/',
  },
  {
    id: 'koki-nagano', name: 'Koki Nagano', first: 'Koki', company: 'NVIDIA', team: 'AI-Mediated Reality and Interaction · AMRI',
    approach: 'hiring', fit: 'core', location: '미국 배치 여부 확인 필요 · 공고에 위치 미명시', tags: ['Full-duplex', 'Multimodal', 'Interaction'],
    hiring: { kind: 'announced', label: '2027 PhD 모집 확인', note: '공식 팀 공고가 연구자에게 직접 이메일을 요청합니다. 지정 제목을 그대로 사용하세요. 미국 배치 여부는 문의에 포함했습니다.', url: amri },
    why: 'DyaPlex의 full-duplex speech-motion, VideoFDB의 vision-speech 평가가 음성·멀티모달 상호작용 연구와 맞닿아 있습니다.',
    advice: '직접 지원 문의. 팀이 요청한 제목을 사용하고 구체적인 연구 방향을 제시하세요. Koki 또는 Shalini 한 명부터 연락하는 편이 좋습니다.',
    links: { email: 'koki.nagano0219@gmail.com', website: 'https://research.nvidia.com/labs/amri/author/koki-nagano/', linkedin: 'https://www.linkedin.com/in/koki-nagano-07926a49/', x: 'https://twitter.com/luminohope' },
    alternative: { name: 'Shalini De Mello · team lead', url: 'https://research.nvidia.com/labs/amri/author/shalini-de-mello/', email: 'shalinig@nvidia.com' },
    sources: [source('공식 2027 PhD 모집 · 직접 이메일 안내', amri, 'hiring'), source('Koki의 2027 채용 글', 'https://www.linkedin.com/posts/koki-nagano-07926a49_robot-activity-7505337145272741889-4GQO', 'hiring'), source('AMRI · DyaPlex / VideoFDB', 'https://research.nvidia.com/labs/amri/')],
    papers: ['duplex', 'audio'], subject: 'Seeking Research Internship 2027',
    email: `Hi Koki,\n\nI’m writing in response to AMRI’s 2027 research internship announcement. I’m a CS PhD candidate at UMass Amherst with Amir Houmansadr, studying speech and multimodal models. My recent Dolby internship focused on full-duplex speech safety, including DuplexJail; my audio-LLM work appeared at COLM 2025.\n\nAMRI’s DyaPlex and VideoFDB are especially relevant to my interest in evaluating interactive agents under interruptions and changing speaker context. I’m currently investigating how updated speaker or authorization evidence should affect pending actions, and would be excited to explore broader multimodal interaction research as well.\n\nCould this direction fit a summer 2027 PhD internship with AMRI, and would a US-based placement be possible?${signature}`,
    dm: 'Hi Koki — I saw AMRI’s 2027 internship announcement. I’m a UMass Amherst PhD candidate, recently at Dolby working on full-duplex speech safety (DuplexJail). DyaPlex and VideoFDB connect closely to my interest in evaluating interactive speech agents. Could this fit a US-based summer 2027 internship? I can email a brief research summary and CV using the requested subject. https://jrohsc.github.io/',
  },
  {
    id: 'jonathan-petit', name: 'Jonathan Petit', first: 'Jonathan', company: 'Qualcomm', team: 'AI security research · existing collaborator',
    approach: 'warm', fit: 'core', location: '미국 · 팀 배치 문의', tags: ['Audio security', 'Authorization', 'Existing collaborator'],
    hiring: { kind: 'pool', label: '2027 미국 PhD 관심 등록 · 팀 TO 미확인', note: '10/7 재확인: 미국 Summer 2027 PhD 관심 등록 양식이 열려 있습니다. AI research·secure AI·audio/speech가 관심 분야에 포함됩니다. 고용 지원서가 아니며 개별 공고 지원은 별도입니다. 인턴 종료 후 최소 한 학기 재학 조건이 있습니다. 기존 ML/AI 공고는 BS/MS/PhD 통합 Engineering 채용으로, Jonathan 팀 배치를 보장하지 않습니다.', url: 'https://careers.qualcomm.com/events/candidate/registration?plannedEventId=Jn9gMpk5A', linkLabel: 'PhD 관심 등록' },
    why: 'CodecAttack 공동저자 관계가 있어 연구 맥락을 새로 설명할 필요가 적습니다. AI 보안 연구팀에서 프로젝트 연속성을 논의할 수 있습니다.',
    advice: '기존 대화 스레드로 바로 물으세요. CodecAttack 이후 하고 싶은 연구와 2027 호스팅 가능성을 짧게 제시하고, 없으면 적합한 팀 연결을 부탁하세요.',
    links: { linkedin: 'https://www.linkedin.com/in/jonathan-petit-03193813' },
    alternative: { name: 'Jean-Philippe Monteuuis · CodecAttack coauthor', url: 'https://www.linkedin.com/in/jeanphilippemonteuuis' },
    sources: [source('공식 Summer 2027 미국 PhD 관심 등록 · 지원서와 별개', 'https://careers.qualcomm.com/events/candidate/registration?plannedEventId=Jn9gMpk5A', 'hiring'), source('CodecAttack · 공동연구 근거', papers.codec.url), source('현재 연구·소속 · Jonathan 프로필', 'https://www.linkedin.com/in/jonathan-petit-03193813'), source('공식 ML/AI Summer 2027 · 통합 채용', 'https://careers.qualcomm.com/careers/job/446720740525', 'hiring'), source('공식 Security Summer 2027 · 통합 채용', 'https://careers.qualcomm.com/careers/job/446720740636', 'hiring')],
    papers: ['codec', 'duplex'], subject: 'Summer 2027 research internship — continuing our audio security work',
    email: `Hi Jonathan,\n\nI’m planning for summer 2027 and wanted to ask whether your team might be able to host me as a PhD research intern. I’d be excited to build on our CodecAttack collaboration.\n\nFollowing my Dolby internship on full-duplex speech safety, I’m now investigating how revised speaker or authorization evidence should invalidate pending voice-agent tool actions. This could be an interesting extension from audio-model robustness to the security of interactive systems.\n\nDo you see a potential project and hosting opportunity with your team? If another Qualcomm team would be a better fit, I’d appreciate your advice on whom to contact. I also found Qualcomm’s Summer 2027 US PhD interest form. Would you recommend that route alongside a specific internship application?${signature}`,
    dm: 'Hi Jonathan — I’m planning for summer 2027 and wondered whether your team could potentially host me as a PhD research intern, building on CodecAttack. I’m now exploring authorization for pending tool actions in full-duplex voice agents after my Dolby internship. Would this be worth discussing as a possible project, or is there another Qualcomm team you’d suggest?',
  },
  {
    id: 'virat-shejwalkar', name: 'Virat Shejwalkar', first: 'Virat', company: 'Google DeepMind', team: 'AI safety · existing collaborator',
    approach: 'warm', fit: 'core', location: '미국 호스팅 팀·배치 문의', tags: ['Audio LLMs', 'Alignment', 'Existing collaborator'],
    hiring: { kind: 'unannounced', label: unknown, note: '공동연구 관계와 공개 소속은 확인되지만 2027 개인 멘토 슬롯은 확인되지 않았습니다.' },
    why: 'COLM 2025와 audio fine-tuning safety 공동연구 경험을 바탕으로, 다음 프로젝트 및 Google 내 관련 팀 소개를 직접 논의할 수 있습니다.',
    advice: '직접 문의가 자연스럽습니다. 기존 스레드에서 새 연구 질문을 한 문단으로 업데이트하고 호스팅 또는 관련 팀 추천을 물으세요.',
    links: { email: 'vshejwalkar@google.com', linkedin: 'https://www.linkedin.com/in/virat-shejwalkar-8659a439' },
    sources: [source('현재 소속 · LinkedIn', 'https://www.linkedin.com/in/virat-shejwalkar-8659a439'), source('공개 업무 연락처 · PoPETs 논문', 'https://petsymposium.org/popets/2025/popets-2025-0079.pdf'), source('Audio fine-tuning · 공동연구', papers.finetune.url)],
    papers: ['audio', 'finetune'], subject: 'Summer 2027 internship plans and a possible next research direction',
    email: `Hi Virat,\n\nI’m starting to plan for summer 2027 and wanted to ask whether a PhD research internship with your team might be possible. I’d be excited to continue our work on audio-LLM safety.\n\nAfter my Dolby internship, I’ve been exploring continuous authorization in full-duplex voice agents: when new speaker evidence arrives, how should it change or invalidate an action that is already pending? I’m interested both in this direction and in broader questions around audio-model alignment and evaluation.\n\nDo you think there could be a suitable project with your team for a US-based internship? If a speech or interactive-agent team would be a closer match, I’d appreciate your recommendation.${signature}`,
    dm: 'Hi Virat — I’m planning summer 2027 and wanted to ask whether a US-based PhD internship with your team could be possible. I’d love to continue our audio-LLM safety work. I’m also exploring continuous authorization for pending actions in full-duplex voice agents after Dolby. Would this fit your team’s plans, or is there a speech/agent team you’d recommend?',
  },
  {
    id: 'deepak-chandran', name: 'Deepak Chandran', first: 'Deepak', company: 'Dolby', team: 'Full-duplex speech · 2026 internship mentor',
    approach: 'warm', fit: 'core', location: 'San Francisco / Sunnyvale / Atlanta · 공식 공고', tags: ['Full-duplex', 'Speech', 'Former mentor'],
    hiring: { kind: 'announced', label: '2027 미국 PhD 모집 · 10/15 우선 검토', note: 'Dolby ATG의 2027 PhD 인턴 공고는 10/2 게시, 10/15까지 지원을 우선 권장합니다. Rolling review이며 10/15는 마감 확정일이 아닙니다. Deepak/Andrea의 개인 멘토 슬롯은 별도 문의하세요.', url: 'https://careers.dolby.com/job/San-Francisco-PhD-Research-Intern-%28Summer-2027%29-CA-94101/1436075000/' },
    why: '가장 최근 인턴 멘토이자 DuplexJail 공동저자입니다. 현재 연구를 후속 프로젝트로 이어갈 가능성을 가장 구체적으로 논의할 수 있습니다.',
    advice: '가장 직접적으로 물어도 좋습니다. 이미 아는 자기소개는 줄이고 복귀 인턴·후속 프로젝트 가능성을 먼저 물으세요. 기존 Deepak/Andrea 스레드를 권합니다.',
    links: { linkedin: 'https://www.linkedin.com/in/deepak-chandran-4979b29a' },
    sources: [source('공식 Summer 2027 PhD 모집 · 10/15 우선 검토', 'https://careers.dolby.com/job/San-Francisco-PhD-Research-Intern-%28Summer-2027%29-CA-94101/1436075000/', 'hiring'), source('현재 소속·연구 · LinkedIn', 'https://www.linkedin.com/in/deepak-chandran-4979b29a'), source('DuplexJail · 공동연구', papers.duplex.url)],
    papers: ['duplex'], subject: 'Summer 2027 — possible follow-up to our full-duplex work',
    email: `Hi Deepak,\n\nI really enjoyed working with you and Andrea this summer. I saw Dolby’s Summer 2027 PhD internship posting and wanted to ask whether a return internship with your team might be possible.\n\nI’m exploring a follow-up direction to our full-duplex work: how an agent should revise or cancel pending tool actions when speaker identity or authorization evidence changes during the interaction. I’d also be happy to shape a project around the team’s broader speech and multimodal priorities.\n\nWould this be a useful direction to discuss for next summer? I noticed the October 15 priority date and would appreciate your advice on project fit and the application route.${signature}`,
    dm: 'Hi Deepak — I’m planning for summer 2027 and wanted to ask about a possible return research internship. I’m exploring authorization updates for pending actions in full-duplex voice agents as a follow-up direction, and would also be interested in the team’s broader priorities. Would it make sense to discuss a potential project with you and Andrea?',
  },
  {
    id: 'desh-raj', name: 'Desh Raj', first: 'Desh', company: 'NVIDIA', team: 'NeMo Speech AI · joined January 2026',
    approach: 'research', fit: 'core', location: '미국 호스팅 가능 여부 문의', tags: ['Speech LLMs', 'Full-duplex', 'Speaker attribution'],
    hiring: { kind: 'unannounced', label: unknown, note: '현재 개인 홈페이지가 NVIDIA 소속을 명시합니다. 과거 Meta 인턴 공고는 사용하지 않습니다. 2027 호스팅 여부는 미확인입니다.' },
    why: 'Speech LLM·full-duplex 모델과 다중 화자 음성 연구 경험이 현재의 speaker evidence 및 실시간 상호작용 질문과 가깝습니다.',
    advice: '연구 접점을 설명한 짧은 이메일을 권합니다. 보안으로만 한정하지 않고 interruption 평가·speaker attribution·speech LLM 신뢰성도 관심 범위로 제시하세요.',
    links: { email: 'r.desh26@gmail.com', website: 'https://desh2608.github.io/', linkedin: 'https://linkedin.com/in/rdesh26', x: 'https://twitter.com/rdesh26' },
    sources: [source('현재 소속·연구·공개 이메일', 'https://desh2608.github.io/')],
    papers: ['duplex', 'audio'], subject: '2027 PhD internship inquiry — speech LLMs and full-duplex interaction',
    email: `Hi Desh,\n\nI saw that you’re working on speech LLMs and full-duplex voice models at NVIDIA. I’m a CS PhD candidate at UMass Amherst with Amir Houmansadr, and my recent Dolby research internship focused on full-duplex speech safety, including DuplexJail. I also worked on multilingual audio-LLM evaluation at COLM 2025.\n\nI’m now investigating how changes in speaker evidence should affect an interactive agent’s pending actions. More broadly, I’m interested in robust speech interaction, speaker attribution, and evaluation under interruptions.\n\nWould you be considering US-based PhD research interns for summer 2027 on related problems? I’d be glad to send a concise research summary and CV if there might be a fit.${signature}`,
    dm: 'Hi Desh — I’m a UMass Amherst PhD candidate, recently at Dolby researching full-duplex speech safety (DuplexJail). Your NVIDIA work on speech LLMs and full-duplex models is closely aligned with my interests in interruptions, speaker evidence, and interactive evaluation. Would you be considering US PhD research interns for summer 2027? https://jrohsc.github.io/',
  },
  {
    id: 'xiaodong-liu', name: 'Xiaodong Liu', first: 'Xiaodong', company: 'Microsoft', team: 'Microsoft Research · post-training / safety alignment',
    approach: 'research', fit: 'core', location: 'Redmond, WA · 호스팅 문의', tags: ['Alignment', 'Multimodal', 'Post-training'],
    hiring: { kind: 'unannounced', label: unknown, note: '현재 연락처 페이지에서 internship inquiries를 받는다고 명시합니다. 특정 2027 모집 공고는 미확인입니다.' },
    why: 'Audio LLM의 benign fine-tuning과 안전 정렬 연구가 post-training·alignment 연구에 직접 연결됩니다.',
    advice: '현재 사이트에서 인턴 문의를 환영하므로 이메일로 명확하게 물으세요. 과거 채용 글 대신 현재 연구와 공개 연락 안내를 근거로 삼습니다.',
    links: { email: 'xiaodl@microsoft.com', website: 'https://xiaodongagi.github.io/contact.html', linkedin: 'https://www.linkedin.com/in/xiaodong-liu-7a17a135' },
    sources: [source('현재 연락 안내 · internships 명시', 'https://xiaodongagi.github.io/contact.html'), source('현재 연구 · post-training / alignment', 'https://xiaodongagi.github.io/index.html'), source('MSR 공식 프로필', 'https://www.microsoft.com/en-us/research/people/xiaodl/')],
    papers: ['finetune', 'bias'], subject: 'Summer 2027 PhD internship inquiry — multimodal safety and post-training',
    email: `Hi Xiaodong,\n\nI’m a CS PhD candidate at UMass Amherst with Amir Houmansadr. Your work on post-training and safety alignment connects closely to my research on how benign fine-tuning affects audio-LLM safety, as well as multimodal backdoors. My related work includes COLM 2025 and USENIX Security 2025 papers.\n\nI recently completed a Dolby research internship on full-duplex speech models. I’m interested in understanding how alignment and evaluation should extend to multimodal models operating in ongoing, interactive settings.\n\nYour contact page mentions internship inquiries. Would you be considering US-based PhD research interns for summer 2027 working on these questions? I’d be happy to share my CV and a brief proposal.${signature}`,
    dm: 'Hi Xiaodong — I’m a UMass Amherst PhD candidate working on audio-LLM fine-tuning safety and multimodal backdoors, with related COLM/USENIX Security work. Your post-training and safety-alignment research seems like a strong fit. Would you be considering US PhD research interns for summer 2027? https://jrohsc.github.io/',
  },
  {
    id: 'giorgio-severi', name: 'Giorgio Severi', first: 'Giorgio', company: 'Microsoft', team: 'AI Red Team',
    approach: 'research', fit: 'core', location: '미국 팀 배치·근무지 문의', tags: ['Agent security', 'Red teaming', 'Multimodal'],
    hiring: { kind: 'unannounced', label: unknown, note: '현재 AI Red Team 연구·소속은 확인했습니다. MSR Security 그룹의 별도 공고를 이 팀의 채용 근거로 사용하지 않습니다.' },
    why: '멀티모달 및 agent security 연구와 사용자의 B², audio fine-tuning, pending-action authorization이 연결됩니다.',
    advice: '연구 관련성을 짚은 짧은 DM으로 2027 인턴 계획을 문의하세요. 팀에서 확인된 취약점이라고 주장하지 않고 본인의 탐구 방향으로 설명합니다.',
    links: { website: 'https://severi.xyz/', linkedin: 'https://www.linkedin.com/in/giorgioseveri' },
    sources: [source('현재 소속·연구', 'https://severi.xyz/'), source('Microsoft 공식 AI safety 연구 소개', 'https://www.microsoft.com/en-us/security/blog/author/giorgio-severi/')],
    papers: ['bias', 'finetune'], subject: '2027 PhD internship inquiry — multimodal and agent security',
    email: `Hi Giorgio,\n\nI’m a CS PhD candidate at UMass Amherst with Amir Houmansadr. Your work on multimodal and agent security at Microsoft’s AI Red Team is closely related to my research on audio-LLM safety and generative-model backdoors, including B² at USENIX Security 2025.\n\nAfter a Dolby internship on full-duplex speech safety, I’m investigating how revised speaker or authorization evidence should prevent an already-pending agent action from executing on stale assumptions. I’m interested in broader red-teaming and evaluation problems as well.\n\nWould your team be considering US-based PhD research interns for summer 2027 with this background? I’d be glad to share my CV and a short research summary.${signature}`,
    dm: 'Hi Giorgio — I’m a UMass Amherst PhD candidate researching audio-LLM safety, multimodal backdoors, and authorization for voice-agent actions. Your AI Red Team research looks closely related; my work includes B² (USENIX Security 2025) and a recent Dolby full-duplex internship. Would your team consider US PhD research interns for summer 2027? https://jrohsc.github.io/',
  },
  {
    id: 'sangho-lee', name: 'Sangho Lee', first: 'Sangho', company: 'Microsoft', team: 'MSR Security Research Group',
    approach: 'hiring', fit: 'core', location: 'Redmond, WA · 공식 공고', tags: ['Systems security', 'Agent security', 'Authorization'],
    hiring: { kind: 'group', label: 'PhD 공고 있음 · 연도 미지정', note: 'Security Research Group의 공식 PhD 인턴 공고가 2026-10-01에 게시됐습니다. 2027 시기와 Sangho 개인의 멘토 여부는 별도 확인이 필요합니다.', url: msr },
    why: '모델의 인식 오류뿐 아니라 인증 증거 변경 이후 실행 직전 권한 검증이라는 시스템 보안 문제로 연구를 설명할 수 있습니다.',
    advice: '공식 지원 후 짧은 연구 문의를 권합니다. 아래 초안은 아직 지원했다고 가정하지 않습니다. 지원했다면 직접 문장을 바꾸고 requisition ID를 덧붙이세요.',
    links: { email: 'Sangho.Lee@microsoft.com', website: 'https://www.microsoft.com/en-us/research/people/sanghle/' },
    sources: [source('공식 PhD 인턴 공고 · Security Research Group', msr, 'hiring'), source('그룹 연구자·공개 업무 이메일', 'https://www.microsoft.com/en-us/research/people/sanghle/')],
    papers: ['duplex', 'spill'], subject: 'MSR Security internship inquiry — authorization for interactive agents',
    email: `Hi Sangho,\n\nI saw the current PhD internship posting for the MSR Security Research Group. I’m a CS PhD candidate at UMass Amherst with Amir Houmansadr, working on multimodal AI and agent security, with publications at USENIX Security, COLM, and NeurIPS.\n\nMy current research asks how updated speaker or authorization evidence should invalidate pending tool actions in full-duplex voice agents. I’m particularly interested in the systems boundary between accepting new evidence and allowing an external action to commit. This follows my recent Dolby internship on full-duplex speech safety.\n\nCould this direction fit the group’s internship research, and might summer 2027 be a suitable timing? I’d appreciate your guidance on project fit alongside the official application process.${signature}`,
    dm: 'Hi Sangho — I saw the MSR Security Research Group’s PhD internship posting. I’m a UMass Amherst PhD candidate working on multimodal/agent security, currently studying how updated authorization evidence should invalidate pending voice-agent actions. Could this systems-security direction fit the group, potentially for summer 2027? https://jrohsc.github.io/',
  },
  {
    id: 'alexander-richard', name: 'Alexander Richard', first: 'Alexander', company: 'Meta', team: 'Reality Labs · audio / multimodal interaction',
    approach: 'research', fit: 'core', location: 'Pittsburgh, PA · 호스팅 문의', tags: ['Speech', 'Multimodal', 'Realtime interaction'],
    hiring: { kind: 'unannounced', label: unknown, note: '현재 연구·연락처는 공개돼 있으나 2027 인턴 모집은 확인되지 않았습니다.' },
    why: 'Audio-driven real-time telepresence와 AVFlow·Seamless Interaction의 멀티모달 대화 연구가 맞습니다. 보안을 필수 주제로 내세울 필요가 없습니다.',
    advice: 'Speech interaction과 평가 관점으로 접근하세요. 현재 연구를 한 예시로 제시하고 팀의 더 넓은 멀티모달 연구에도 열려 있다고 설명합니다.',
    links: { email: 'richardalex@meta.com', website: 'https://alexanderrichard.github.io/' },
    sources: [source('현재 Meta 소속·연구·공개 이메일', 'https://alexanderrichard.github.io/')],
    papers: ['duplex', 'confetti'], subject: 'Summer 2027 PhD internship inquiry — speech and multimodal interaction',
    email: `Hi Alexander,\n\nI’m a CS PhD candidate at UMass Amherst with Amir Houmansadr. Your research on audio-driven interaction and multimodal conversation, including AVFlow and Seamless Interaction, caught my attention.\n\nI recently completed a Dolby research internship on full-duplex speech models, and my broader work studies audio and multimodal generation, robustness, and evaluation. I’m currently exploring how interactive agents should respond when speaker evidence changes during a conversation. I’d also be very interested in projects on multimodal interaction and evaluation beyond a security-specific framing.\n\nWould you be considering US-based PhD research interns for summer 2027 with this background? I’d be happy to share my CV and a short summary of possible research directions.${signature}`,
    dm: 'Hi Alexander — I’m a UMass Amherst PhD candidate, recently at Dolby working on full-duplex speech models. Your audio-driven and multimodal interaction research connects well to my interests in conversational evaluation and robustness. Would you be considering US PhD research interns for summer 2027? I’m open to broader interaction research beyond security. https://jrohsc.github.io/',
  },
  {
    id: 'zeyu-jin', name: 'Zeyu Jin', first: 'Zeyu', company: 'Adobe', team: 'Adobe Research · generative audio / speech',
    approach: 'research', fit: 'core', location: '미국 팀 배치·근무지 문의', tags: ['Generative audio', 'Speech', 'Evaluation'],
    hiring: { kind: 'unannounced', label: unknown, note: 'Adobe 공식 연구 프로필과 연구 분야는 확인했습니다. 2027 멘토 슬롯은 미확인입니다.' },
    why: '음성 생성·enhancement·음악·품질 평가가 audio LLM 및 Bob’s Confetti 연구와 연결됩니다. 현재 authorization 프로젝트만으로 소개할 필요는 없습니다.',
    advice: '생성 음성의 품질·평가·robustness로 폭을 넓혀 문의하세요. 진행 중인 보안 과제를 팀의 필수 연구 목표처럼 제안하지 않습니다.',
    links: { website: 'https://research.adobe.com/person/zeyu-jin/', linkedin: 'https://www.linkedin.com/in/zeyu-jin-5b860424' },
    sources: [source('Adobe 공식 연구 프로필', 'https://research.adobe.com/person/zeyu-jin/'), source('LinkedIn · 연락 경로', 'https://www.linkedin.com/in/zeyu-jin-5b860424')],
    papers: ['confetti', 'audio'], subject: '2027 PhD internship inquiry — generative audio and evaluation',
    email: `Hi Zeyu,\n\nI’m a CS PhD candidate at UMass Amherst with Amir Houmansadr, researching audio and multimodal generative models. Your work on generative speech, audio enhancement, and evaluation at Adobe Research is closely aligned with my interests.\n\nMy work includes multilingual audio-LLM evaluation at COLM 2025 and Bob’s Confetti, a preprint studying phonetic memorization in music and video generation. I also recently completed a Dolby internship on full-duplex speech models. I’d be excited to explore generative-audio evaluation, robustness, or interactive speech research beyond a narrowly security-focused project.\n\nWould you be considering US-based PhD research interns for summer 2027? I’d be happy to share my CV and a brief research summary if there could be a fit.${signature}`,
    dm: 'Hi Zeyu — I’m a UMass Amherst PhD candidate working on audio/multimodal generation and evaluation, including COLM 2025 audio-LLM work and Bob’s Confetti. I recently interned at Dolby on full-duplex speech. Your generative-audio research looks like a strong fit. Would you be considering US PhD research interns for summer 2027? https://jrohsc.github.io/',
  },
  {
    id: 'umar-iqbal', name: 'Umar Iqbal', first: 'Umar', company: 'NVIDIA', team: 'Dynamic Agents and Interaction Research · DAIR',
    approach: 'hiring', fit: 'adjacent', location: 'Santa Clara, CA · 공식 공고', tags: ['Human interaction', 'Embodied AI', 'Multimodal'],
    hiring: { kind: 'announced', label: '2027 미국 PhD 모집 확인', note: 'JR2025405 · human data 기반 embodied skills / robot learning 자리입니다. 음성 연구 전용 자리는 아닙니다.', url: dair },
    why: '멀티모달 인간 상호작용으로 분야를 넓힐 경우 후보입니다. 공고의 핵심인 human motion·robot learning 경험은 CV에서 확인되지 않아 우선순위를 낮췄습니다.',
    advice: '공식 지원과 구체적인 적합성 문의. 본인에게 없는 robotics 경력을 암시하지 말고, interaction evaluation 경험이 프로젝트에 기여할 수 있는지 먼저 확인하세요.',
    links: { email: 'uiqbal@nvidia.com', website: 'https://www.umariqbal.info/', linkedin: 'https://www.linkedin.com/in/iqbalu' },
    sources: [source('공식 2027 PhD 공고', dair, 'hiring'), source('Umar의 2027 채용 글', 'https://www.linkedin.com/posts/iqbalu_phd-research-intern-learning-embodied-skills-activity-7508672573933690880-y9CL', 'hiring'), source('현재 연구·인턴 연락 안내', 'https://www.umariqbal.info/')],
    papers: ['duplex', 'confetti'], subject: '2027 DAIR PhD internship — research fit inquiry (JR2025405)',
    email: `Hi Umar,\n\nI saw your 2027 PhD internship announcement on learning embodied skills from human data. I’m a CS PhD candidate at UMass Amherst with Amir Houmansadr, working on audio and multimodal models, with a recent Dolby internship on full-duplex speech interaction.\n\nMy strongest background is in evaluation and robustness of interactive generative models, rather than robot learning. I’m interested in whether this perspective could contribute to evaluating human-agent interaction or multimodal behavior in DAIR’s projects.\n\nBefore applying to JR2025405, I wanted to ask whether that background could be relevant to the available projects, or whether you are primarily seeking prior human-motion and robotics experience. I’d be happy to share my CV.${signature}`,
    dm: 'Hi Umar — I saw your 2027 DAIR internship post (JR2025405). I’m a UMass Amherst PhD candidate focused on audio/multimodal evaluation, recently at Dolby on full-duplex speech. My background is interactive-model robustness rather than robot learning. Could that perspective fit any of the projects, or is prior robotics experience central? https://jrohsc.github.io/',
  },
  {
    id: 'marco-pavone', name: 'Marco Pavone', first: 'Marco', company: 'NVIDIA', team: 'Autonomous Systems and Physical AI Research · ASPIRE',
    approach: 'hiring', fit: 'adjacent', location: 'Santa Clara, CA · 공식 공고', tags: ['Agent safety', 'Physical AI', 'Reasoning'],
    hiring: { kind: 'announced', label: '2027 미국 PhD 모집 확인', note: 'JR2024171 · autonomous systems / physical AI 자리입니다. 음성·보안 전용 자리는 아니며 관련 분야에 대한 관심과 프로젝트 적합성이 필요합니다.', url: aspire },
    why: 'Reasoning·agentic workflow·closed-loop safety로 확장할 경우 후보입니다. 현재 음성 연구와의 직접성은 AMRI·NeMo보다 낮습니다.',
    advice: '공식 지원 경로를 우선하고 연구 방향이 맞는지 짧게 문의하세요. 현재 authorization 연구를 physical AI에서 이미 검증한 결과처럼 표현하지 않습니다.',
    links: { linkedin: 'https://www.linkedin.com/in/marco-pavone-stanford/' },
    sources: [source('공식 2027 PhD 공고', aspire, 'hiring'), source('Marco의 2027 채용 글', 'https://www.linkedin.com/posts/marco-pavone-stanford_phd-research-intern-autonomous-systems-and-activity-7505408703202766848-tnaN', 'hiring')],
    papers: ['duplex', 'spill'], subject: '2027 ASPIRE PhD internship — agent safety research fit (JR2024171)',
    email: `Hi Marco,\n\nI saw your announcement for ASPIRE’s 2027 PhD research internships. I’m a CS PhD candidate at UMass Amherst with Amir Houmansadr, researching multimodal and interactive-agent security. My work includes COLM and USENIX Security papers and a recent Dolby internship on full-duplex speech models.\n\nI’m currently studying how agents should invalidate pending actions when their supporting authorization evidence changes. I’m interested in exploring how related questions about evidence, intervention, and action execution could inform closed-loop agent safety. My existing experience is in speech and web agents rather than autonomous vehicles or robotics.\n\nCould this perspective be relevant to any ASPIRE internship projects under JR2024171? I’d appreciate your guidance on fit.${signature}`,
    dm: 'Hi Marco — I saw ASPIRE’s 2027 PhD internship announcement (JR2024171). I’m a UMass Amherst PhD candidate studying interactive-agent safety, currently focusing on invalidating pending actions when authorization evidence changes. My background is speech/web agents rather than robotics. Could this perspective be relevant to any ASPIRE projects? https://jrohsc.github.io/',
  },
].map(c => ({ ...c, verifiedAt: rechecked.has(c.id) ? reviewedAt : '2026-10-06' }));

export function defaultDraft(contact, mode) {
  if (mode === 'dm') return { subject: '', body: contact.dm };
  if (mode === 'followup') return { subject: `Re: ${contact.subject}`, body: `Hi ${contact.first},\n\nJust following up on my note about a possible summer 2027 PhD research internship. I’d still be interested in exploring whether my background could fit your team’s plans. I understand if the timing or availability isn’t clear yet.\n\nThanks for your time,\nJaechul` };
  return { subject: contact.subject, body: contact.email };
}
