import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Check,CheckCheck,Bookmark,ShieldAlert,BookOpen,Clock,SlidersHorizontal,ChevronDown,ExternalLink} from 'lucide-react';
import {groupDevelopments,selectBriefing,prioritize,describeDevelopment} from '../shared/briefing.js';
import {FORESTS} from '../shared/landscape.js';
import {TOPIC_DEFINITIONS} from '../shared/topics.js';
import './briefing.css';
import {BlogPulse} from './LabBlogs.jsx';
import {affiliationLabel} from '../shared/affiliations.js';
const readStore=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const date=ms=>new Date(ms).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const compact=(s,n=230)=>s.length>n?s.slice(0,n).replace(/\s+\S*$/,'')+'…':s;
export default function Briefing({blogs,items,watch,saved,onSave,onOpen,onNavigate,onSettings,sources}){
 const [previous]=useState(()=>{const p=readStore('sentinel-briefing-visit',null);return p?.groups&&Number.isFinite(p.at)?p:null});
 const [mode,setMode]=useState(previous?'visit':'week'),[read,setRead]=useState(()=>readStore('sentinel-briefing-read',{})),[showRead,setShowRead]=useState(false),[area,setArea]=useState(null),[keyword,setKeyword]=useState(null),[expanded,setExpanded]=useState(null),[storageError,setStorageError]=useState(false);
 const groups=useMemo(()=>groupDevelopments(items.filter(p=>(p.kind||'paper')==='paper'),watch),[items,watch]);
 const selections=useMemo(()=>selectBriefing(groups,{previous,mode,read}),[groups,previous,mode,read]);
 const latestGroups=useRef(groups);latestGroups.current=groups;
 useEffect(()=>{
  const persist=()=>{if(!latestGroups.current.length||document.visibilityState==='hidden')return;try{const existing=readStore('sentinel-briefing-visit',{groups:{}});const updated={...existing.groups,...Object.fromEntries(latestGroups.current.map(g=>[g.id,g.signature]))};localStorage.setItem('sentinel-briefing-visit',JSON.stringify({at:Date.now(),groups:Object.fromEntries(Object.entries(updated).slice(-20000))}));}catch{setStorageError(true)}};
  persist();document.addEventListener('visibilitychange',persist);return()=>document.removeEventListener('visibilitychange',persist);
 },[groups]);
 useEffect(()=>{try{localStorage.setItem('sentinel-briefing-read',JSON.stringify(read))}catch{setStorageError(true)}},[read]);
 const groupTopics=area?FORESTS.find(g=>g.name===area)?.topics.map(i=>TOPIC_DEFINITIONS[i].name):null;
 const visible=selections.filter(g=>(showRead||!g.read)&&(!keyword||g.matches.includes(keyword))&&(!groupTopics||g.topics.some(t=>groupTopics.includes(t))));
 const research=prioritize(visible.filter(g=>g.kind==='research'),3);
 const security=prioritize(visible.filter(g=>g.kind==='security'),3);
 const news=prioritize(visible.filter(g=>g.kind==='news'),3);
 const watchMatches=selections.filter(g=>g.matches.length&&!g.read).length;
 const reviewed=selections.filter(g=>g.read).length;
 const areas=FORESTS.map(a=>({...a,count:selections.filter(g=>g.topics.some(t=>a.topics.some(i=>TOPIC_DEFINITIONS[i].name===t))).length}));
 const activeSources=sources.filter(s=>s.status==='connected').length;
 const pending=sources.some(s=>s.status==='loading');
 const failed=sources.filter(s=>!['loading','connected'].includes(s.status));
 const currentHeading=mode==='visit'&&previous?'Since your last visit.':mode==='day'?'Your day, in perspective.':'Your week, in perspective.';
 function mark(g){setRead(old=>{const next={...old};if(old[g.id]===g.signature)delete next[g.id];else next[g.id]=g.signature;return next})}
 function resetWindow(){setMode('week');setShowRead(true);setArea(null);setKeyword(null)}
 function status(g){if(g.read)return 'Reviewed';if(mode==='visit')return g.change==='updated'?'Updated':g.lastEvent<previous.at?'Newly indexed':'New';return 'Unreviewed'}
 return <div className="daily-briefing">
 <div className="briefing-topline"><span><i/> PERSONAL INTELLIGENCE BRIEFING</span><span>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</span></div>
 <section className="briefing-hero"><div><h1>{currentHeading}</h1><p>{previous&&mode==='visit'?`Changes since ${new Date(previous.at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}.`:'A focused view of AI safety and cybersecurity research.'} Start with what matters to your work.</p></div><div className="briefing-window"><Clock size={15}/><select aria-label="Briefing time window" value={mode} onChange={e=>{setMode(e.target.value);setArea(null)}}>{previous&&<option value="visit">Since last visit</option>}<option value="day">Last 24 hours</option><option value="week">Last 7 days</option></select></div></section>
 <div className="briefing-source-line"><span>{pending?'Sources are updating; this briefing may change.':failed.length?`${failed.length} source groups delayed; available records shown.`:`${activeSources} source groups connected.`}</span><details><summary>Source status <ChevronDown size={12}/></summary><div>{sources.map(s=><p key={s.name}><span>{s.name}</span><strong>{s.status}</strong></p>)}<button onClick={onSettings}>Full source coverage <ArrowUpRight size={12}/></button></div></details></div>
 {storageError&&<div className="briefing-storage">Browser storage is unavailable. Visit history and review status may not persist.</div>}
 <section className="briefing-glance" aria-label="Briefing at a glance"><div><span className="glance-label"><BookOpen size={15}/> RESEARCH</span><strong>{selections.filter(g=>g.kind==='research').length}<small> developments</small></strong><p>Paper versions grouped where identifiable.</p></div><button onClick={()=>onNavigate('Conferences')}><span className="glance-label"><BookOpen size={15}/> CONFERENCES</span><strong>{selections.filter(g=>g.members.some(p=>p.publicationType==='conference')).length}<small> proceedings papers</small></strong><p>Venue labels from publication metadata. <ArrowUpRight size={12}/></p></button><button onClick={()=>{setArea(null);onNavigate('Watchlist')}}><span className="glance-label"><Bookmark size={15}/> FOR YOU</span><strong>{watchMatches}<small> unread watchlist matches</small></strong><p>Based on your saved keywords. <ArrowUpRight size={12}/></p></button></section>
 <section className="briefing-areas"><div className="briefing-section-title"><div><span className="briefing-kicker">THE WIDER VIEW</span><h2>Where the activity is.</h2></div><button onClick={()=>onNavigate('Overview')}>Explore the landscape <ArrowUpRight size={14}/></button></div><div className="area-overview">{areas.map((a,i)=><button key={a.name} className={area===a.name?'area-selected':''} onClick={()=>setArea(area===a.name?null:a.name)} aria-pressed={area===a.name}><span className="area-number">0{i+1}</span><strong>{a.name}</strong><div className="area-meter"><i style={{width:`${a.count/Math.max(1,...areas.map(g=>g.count))*100}%`}}/></div><span>{a.count} developments {area===a.name?'· selected':''}</span></button>)}</div><p className="briefing-fineprint">Counts describe this briefing’s indexed sample. Areas overlap; these are activity counts, not growth or importance scores.</p></section>
 <div className="briefing-reading-bar"><span>{reviewed} of {selections.length} reviewed <i><b style={{width:`${reviewed/Math.max(1,selections.length)*100}%`}}/></i></span><label><input type="checkbox" checked={showRead} onChange={e=>setShowRead(e.target.checked)}/> Show reviewed</label><button onClick={onSettings}><SlidersHorizontal size={13}/> Tune my watchlist</button></div>
 <div className="briefing-columns"><section className="briefing-research"><div className="briefing-section-title"><div><span className="briefing-kicker">RESEARCH TO UNDERSTAND</span><h2>{keyword?`Following: ${keyword}`:area||'Three things worth a look.'}</h2></div>{(area||keyword)&&<button onClick={()=>{setArea(null);setKeyword(null)}}>Clear filter ×</button>}</div><p className="briefing-selection-note">Selected by watchlist match, updates, and recency, with topic variety. These are reading suggestions, not verified breakthroughs.</p>
 {research.map((g,i)=>{const d=describeDevelopment(g),isSaved=saved.some(p=>p.id===g.primary.id);return <article key={g.id} className={'briefing-story '+(g.read?'story-read':'')}><div className="story-meta"><span className="story-index">0{i+1}</span><span>{g.primary.venue||g.primary.source}</span><span>·</span><time>{date(g.lastEvent)}</time><span className={'story-status '+(g.change==='updated'?'updated':'')}>{status(g)}</span></div><h3><button onClick={()=>setExpanded(expanded===g.id?null:g.id)}>{g.primary.title}</button></h3><div className="story-excerpt"><small>FROM THE ABSTRACT</small><p>{compact(d.excerpt)}</p></div><div className="story-why"><span>Why it surfaced</span><p>{d.why}</p></div><div className="paper-provenance"><span title={g.primary.groupEvidence||'No author affiliations in available metadata'}><strong>Group / institution</strong> {affiliationLabel(g.primary)}</span><span><strong>Venue</strong> {g.primary.venue?`${g.primary.venue}${g.primary.year?' '+g.primary.year:''}`:'arXiv / conference not verified'}</span></div><div className="story-evidence"><span>{g.primary.venue?'Proceedings metadata':'Preprint / venue unverified'}</span>{g.matches.length>0&&<span className="watch-match">Matches: {g.matches.join(', ')}</span>}{g.members.length>1&&<span>{g.members.length} records grouped</span>}</div><div className="story-actions"><button className="briefing-read-button" onClick={()=>setExpanded(expanded===g.id?null:g.id)} aria-expanded={expanded===g.id}>{expanded===g.id?'Close brief':'Read the brief'} <ArrowRight size={13}/></button><button onClick={()=>onSave(g.primary)} aria-label={isSaved?'Unsave briefing paper':'Save briefing paper'}><Bookmark size={15} fill={isSaved?'currentColor':'none'}/>{isSaved?'Saved':'Save'}</button><button onClick={()=>mark(g)} aria-label={g.read?'Mark development unread':'Mark development reviewed'}><Check size={15}/>{g.read?'Reviewed':'Mark reviewed'}</button></div>{expanded===g.id&&<BriefEvidence group={g} detail={d} onOpen={onOpen}/>}</article>})}
 {!research.length&&<div className="briefing-empty"><CheckCheck size={30}/><h3>{pending?'Building your research briefing…':'You’re caught up in this view.'}</h3><p>{pending?'Research and proceedings are arriving from connected sources.':'There are no unreviewed research developments matching these filters.'}</p><button onClick={resetWindow}>Review the last 7 days <ArrowRight size={14}/></button></div>}
 </section><aside className="briefing-side"><BlogPulse blogs={blogs} onOpen={onOpen} onNavigate={onNavigate}/><section className="briefing-watch"><div className="briefing-section-title"><div><span className="briefing-kicker">YOUR RESEARCH LENS</span><h2>Following closely.</h2></div><Bookmark size={18}/></div><p className="briefing-selection-note">Your keywords shape which papers surface first.</p>{watch.map(w=><button className={'briefing-watch-row '+(keyword===w?'selected-keyword':'')} key={w} onClick={()=>setKeyword(keyword===w?null:w)}><span>{w}</span><strong>{selections.filter(g=>g.matches.includes(w)&&!g.read).length}</strong><ArrowRight size={12}/></button>)}<button className="briefing-section-link" onClick={onSettings}>Edit your watchlist <SlidersHorizontal size={13}/></button></section><section className="briefing-groups"><div className="briefing-section-title"><div><span className="briefing-kicker">WHO’S PUBLISHING</span><h2>Groups & institutions.</h2></div></div>{Object.entries(selections.reduce((acc,g)=>{for(const name of new Set(g.members.flatMap(p=>p.groups||[])))acc[name]=(acc[name]||0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,n])=><div key={name}><span>{name}</span><strong>{n}</strong></div>)}<p className="briefing-fineprint">Institutions or labs from author affiliations. Missing metadata is not inferred; counts reflect the available sample.</p></section><div className="briefing-note"><BookOpen size={19}/><h3>Read claims. Follow evidence.</h3><p>Briefs use paper metadata and abstract excerpts. “Why it surfaced” explains relevance, not an independent assessment of the findings.</p><button onClick={()=>onNavigate('Conferences')}>Browse conference papers <ArrowUpRight size={13}/></button></div><button className="briefing-section-link" onClick={()=>onNavigate('Overview')}>See the full research landscape <ArrowUpRight size={13}/></button></aside></div>
 <div className="briefing-bottom"><span>Paper versions are grouped using explicit identifiers or an exact title match. Topic similarity alone does not combine papers.</span><button onClick={()=>onNavigate('Research feed')}>Investigate in the terminal <ArrowRight size={14}/></button></div>
 </div>;
}
function BriefEvidence({group:g,detail:d,onOpen}){return <div className="brief-evidence"><h4>{g.kind==='research'?'What the authors report':'What the source reports'}</h4><p>{d.excerpt}</p><h4>Why it matters to this view</h4><p>{d.why}</p><h4>Evidence & limits</h4><p><strong>{d.evidence}.</strong> {d.limit}</p><h4>Publishing groups & venue</h4><p>{affiliationLabel(g.primary)}<br/>{g.primary.venue||'Conference venue not verified'}{g.primary.year?' · '+g.primary.year:''}</p><h4>Inspect the sources</h4>{g.members.map(p=><div className="brief-source" key={p.id}><button onClick={()=>onOpen(p)}>{p.source}{p.venue?' · '+p.venue:''}: {p.cve||p.title}<ArrowRight size={12}/></button><a href={p.url} target="_blank" rel="noreferrer" aria-label={`Open source ${p.source}`}><ExternalLink size={13}/></a>{p.arxivUrl&&<a href={p.arxivUrl} target="_blank" rel="noreferrer">arXiv version ↗</a>}</div>)}<small>Multiple records can describe the same event; this is not independent replication.</small></div>}
