import React,{useMemo,useState} from 'react';
import {ArrowUpRight,Globe,Layers,TrendingUp,GitBranch,BookOpen} from 'lucide-react';
import {analyzeLandscape,FORESTS} from '../shared/landscape.js';
import {TOPIC_DEFINITIONS} from '../shared/topics.js';
import './landscape.css';
const date=n=>new Date(n).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
const pp=n=>n===null?'LOW SAMPLE':`${n>=0?'+':''}${n.toFixed(1)} pp`;
export default function Landscape({papers,conferences,onOpen,onBrowse,onConferences,researchStatus,cyberStatus}){
 const [days,setDays]=useState(14),[kind,setKind]=useState('research'),[focus,setFocus]=useState(null),[week,setWeek]=useState(null),[pair,setPair]=useState(null);
 const model=useMemo(()=>analyzeLandscape(papers,{days,kind}),[papers,days,kind]);
 const ranked=[...model.rows].filter(r=>r.delta!==null).sort((a,b)=>b.delta-a.delta);
 const scope=week===null?{start:model.start,end:model.end}:model.weeks[week];
 const evidence=model.sample.filter(p=>Date.parse(p.published)>=scope.start&&Date.parse(p.published)<scope.end&&(!focus||p.topics.includes(focus))&&(!pair||p.topics.includes(pair))).sort((a,b)=>Date.parse(b.published)-Date.parse(a.published));
 const links=model.pairs.filter(p=>!focus||p.a===focus||p.b===focus).slice(0,6);
 const venueRows=Object.entries(papers.filter(p=>p.publicationType==='conference').reduce((acc,p)=>({...acc,[p.venue]:(acc[p.venue]||0)+1}),{})).sort((a,b)=>b[1]-a[1]);
 function choose(name){setFocus(name);setWeek(null);setPair(null)}
 const peak=Math.max(1,...model.rows.flatMap(r=>r.weekly));
 return <div className="forest-dashboard">
 <div className="forest-toolbar"><div><Globe size={16}/><strong>THE BIG PICTURE</strong><span>Areas → momentum → evidence</span></div><div><select aria-label="Landscape dataset" value={kind} onChange={e=>{setKind(e.target.value);setFocus(null);setPair(null);setWeek(null)}}><option value="research">Research papers</option></select><select aria-label="Trend window" value={days} onChange={e=>{setDays(Number(e.target.value));setWeek(null)}}><option value="7">7 vs previous 7 days</option><option value="14">14 vs previous 14 days</option><option value="30">30 vs previous 30 days</option></select></div></div>
 <div className="forest-method">OBSERVED SAMPLE · {kind==='research'?`arXiv: ${researchStatus} / proceedings: ${conferences.status}`:`Cyber sources: ${cyberStatus}`} · {date(model.start)}–{date(model.end-1)} vs {date(model.priorStart)}–{date(model.start-1)} · Complete UTC days; month/year-only records excluded. Topic share changes are percentage points, not field-wide growth. Source caps and proceedings batches affect counts.</div>
 <div className="forest-summary"><div><small>CURRENT WINDOW / PREVIOUS</small><strong>{model.recent.length.toLocaleString()} <span>/ {model.previous.length.toLocaleString()}</span></strong><p>{kind==='research'?'Deduplicated research papers':'News & vulnerability events'} in the indexed sample</p></div><div><small>LARGEST POSITIVE SHARE SHIFT</small><strong>{ranked[0]?.delta>0?pp(ranked[0].delta):'INSUFFICIENT SIGNAL'}</strong><p>{ranked[0]?.delta>0?ranked[0].name:'Need ≥20 items in each window and ≥5 topic matches'}</p></div><div><small>CONFERENCE PAPERS INDEXED</small><strong>{papers.filter(p=>p.publicationType==='conference').length}<span> / {venueRows.length} venues or series</span></strong><p>Proceedings metadata · preprint duplicates merged where identifiable</p></div></div>
 <div className="forest-top-grid"><section className="panel forest-map"><div className="panel-head"><span><Layers size={13}/> FIELD MAP</span><span className="muted">CLICK AN AREA TO INSPECT</span></div><Terrain rows={model.rows} focus={focus} onChoose={choose}/><div className="forest-map-key"><span>Numbers = current-window items</span><span>Bars = share of current sample</span></div><div className="forest-groups">{FORESTS.map(group=><div className="forest-group" key={group.name}><h3 style={{color:group.color}}>{group.name}</h3>{group.topics.map(i=>{const r=model.rows[i];return <button className={focus===r.name?'focused':''} key={r.name} onClick={()=>choose(r.name)} aria-pressed={focus===r.name}><span className="forest-topic-name">{r.name}</span><strong>{r.current}</strong><span className={'forest-change '+(r.delta>0?'up':r.delta<0?'down':'')}>{pp(r.delta)}</span><i style={{width:`${r.share}%`,background:r.color}}/></button>})}</div>)}</div></section>
 <section className="panel momentum-panel"><div className="panel-head"><span><TrendingUp size={13}/> MOMENTUM</span><span className="muted">SHARE SHIFT</span></div><div className="momentum-labels"><span>AREA</span><span>NOW / PRIOR</span><span>Δ SHARE</span></div>{ranked.slice(0,7).map(r=><button className="momentum-row" key={r.name} onClick={()=>choose(r.name)}><span>{r.name}</span><span>{r.current} / {r.prior}</span><strong className={r.delta>=0?'up':'down'}>{pp(r.delta)}</strong></button>)}{!ranked.length&&<p className="forest-empty">Not enough observations for a stable comparison. Try a wider time window.</p>}<div className="forest-insight"><strong>HOW TO READ THIS</strong><p>A positive change means a topic occupies more of this sample. It does not measure research quality, threat severity, or global growth.</p><p>Use the field map for breadth, the weekly grid for persistence, and overlap to find intersections.</p></div></section></div>
 <div className="forest-bottom-grid"><section className="panel weekly-panel"><div className="panel-head"><span>TOPIC ACTIVITY / 8 WEEKS</span><span className="muted">CLICK A CELL FOR ITS EVIDENCE</span></div><div className="weekly-scroll"><div className="weekly-grid"><span className="weekly-name">WEEK ENDING (UTC)</span>{model.weeks.map(w=><span className="weekly-date" key={w.start}>{date(w.end-1)}</span>)}{model.rows.map(r=><React.Fragment key={r.name}><button className={'weekly-name '+(focus===r.name?'focused':'')} onClick={()=>choose(r.name)}>{r.name}</button>{r.weekly.map((count,i)=><button key={i} className={'heat-cell '+(focus===r.name&&week===i?'focused':'')} style={{background:count?`rgba(255,149,0,${.13+.72*Math.log1p(count)/Math.log1p(peak)})`:'#0a0d12',color:count>peak*.3?'#000':'#ddd'}} aria-label={`${r.name}, week ending ${date(model.weeks[i].end-1)}: ${count} items`} onClick={()=>{setFocus(r.name);setWeek(i);setPair(null)}}>{count||'·'}</button>)}</React.Fragment>)}</div></div><div className="forest-footnote">Common logarithmic color scale · counts shown in every cell · zeros may reflect incomplete source coverage.</div></section>
 <div className="forest-evidence-column"><section className="panel evidence-panel"><div className="panel-head"><span>EVIDENCE / {evidence.length} ITEMS</span><button className="forest-clear" onClick={()=>{setFocus(null);setPair(null);setWeek(null)}}>RESET</button></div><div className="evidence-scope"><strong>{focus||'All areas'}{pair?` ∩ ${pair}`:''}</strong><span>{date(scope.start)}–{date(scope.end-1)}</span></div><div className="evidence-list">{evidence.slice(0,8).map(p=><button key={p.id} onClick={()=>onOpen(p)}><small>{p.venue||p.source} · {date(Date.parse(p.published))}</small><span>{p.title}<ArrowUpRight size={12}/></span></button>)}{!evidence.length&&<p className="forest-empty">No indexed items for this selection.</p>}</div><button className="text-button" onClick={()=>onBrowse(focus,kind,scope,pair)}>OPEN FILTERED FEED <ArrowUpRight size={12}/></button></section>
 <section className="panel overlap-panel"><div className="panel-head"><span><GitBranch size={13}/> TOPIC INTERSECTIONS</span><span className="muted">SHARED PAPERS / EVENTS</span></div>{links.map(p=><button key={p.a+p.b} onClick={()=>{setFocus(p.a);setPair(p.b);setWeek(null)}}><span>{p.a} <b>×</b> {p.b}</span><small>{p.count} shared · {(p.jaccard*100).toFixed(0)}% overlap</small></button>)}{!links.length&&<p className="forest-empty">No intersections with at least 3 shared items in this window.</p>}<div className="forest-footnote">Overlap = shared items ÷ items in either topic. Keyword co-occurrence, not a citation graph.</div></section></div></div>
 <section className="panel venue-panel"><div className="panel-head"><span><BookOpen size={13}/> CONFERENCE RADAR</span><span className="muted">{conferences.status.toUpperCase()} · PROCEEDINGS METADATA</span></div><div className="venue-bars">{venueRows.slice(0,12).map(([venue,count])=><button key={venue} onClick={()=>onConferences(venue)}><span>{venue}</span><i><b style={{width:`${count/venueRows[0][1]*100}%`}}/></i><strong>{count}</strong></button>)}{!venueRows.length&&<p className="forest-empty">{conferences.status==='loading'?'Loading conference metadata…':'No conference records available. Check source status.'}</p>}</div><div className="forest-footnote">All indexed dates · venue/series labels come from source metadata, not inferred acceptance. Indexing may lag proceedings release. <button onClick={()=>onConferences('all')}>Browse conference papers ↗</button></div></section>
 </div>;
}

function Terrain({rows,focus,onChoose}){
 const points=rows.filter(r=>r.delta!==null);
 const range=Math.max(5,...points.map(r=>Math.abs(r.delta)))*1.15;
 const max=Math.max(1,...points.map(r=>r.current));
 const x=d=>310+d/range*245,y=n=>245-Math.log1p(n)/Math.log1p(max)*195;
 const groupFor=name=>FORESTS.find(g=>g.topics.some(i=>TOPIC_DEFINITIONS[i].name===name));
 return <div className="terrain"><svg viewBox="0 0 620 292" role="group" aria-label="Topic activity versus momentum plot"><text x="12" y="17" className="terrain-axis">MORE ACTIVITY ↑</text>{[0,.5,1].map(v=><g key={v}><line x1="55" x2="575" y1={245-v*195} y2={245-v*195}/><text x="45" y={248-v*195} textAnchor="end" className="terrain-axis">{Math.round(Math.expm1(Math.log1p(max)*v))}</text></g>)}<line x1="310" x2="310" y1="30" y2="245" strokeDasharray="3 4"/><text x="65" y="276" className="terrain-axis">← LOWER SHARE</text><text x="310" y="276" textAnchor="middle" className="terrain-axis">0 pp</text><text x="575" y="276" textAnchor="end" className="terrain-axis">HIGHER SHARE →</text>{points.map(r=><g key={r.name} role="button" tabIndex="0" aria-label={`${r.name}: ${r.current} items, ${pp(r.delta)} share change`} onClick={()=>onChoose(r.name)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onChoose(r.name)}}} className="terrain-point"><title>{r.name}: {r.current} current / {r.prior} prior · {pp(r.delta)}</title><circle cx={x(r.delta)} cy={y(r.current)} r={5+Math.sqrt(r.current/max)*15} fill={groupFor(r.name)?.color||r.color} fillOpacity={focus===r.name?'.85':'.35'} stroke={groupFor(r.name)?.color||r.color} strokeWidth={focus===r.name?2.5:1}/><text x={x(r.delta)+8} y={y(r.current)-9} className="terrain-code">{r.code}</text></g>)}{!points.length&&<text x="310" y="145" textAnchor="middle" className="terrain-axis">Waiting for enough comparable observations</text>}</svg><div className="terrain-legend">{FORESTS.map(g=><span key={g.name}><i style={{background:g.color}}/>{g.name}</span>)}</div><div className="forest-footnote">Bubble size = current count; vertical scale is logarithmic. Hover for exact values. Only topics meeting sample thresholds are plotted.</div></div>;
}
