import test from 'node:test';import assert from 'node:assert/strict';
import {assessRelevance,filterRelevantPapers} from './shared/relevance.js';import {parseFeed} from './feed.js';import {parsePaperFigures} from './figures.js';
const ai={categories:['cs.LG'],kind:'paper'};
test('rejects actual broad-query false positives and unrelated uses of security',()=>{for(const title of ['Programmable World Model','Avatar: Toward Autonomous End-to-End Orchestration of Scientific Workflows using LLMs','A New Multimodal Benchmark','Personalization of Recommendations','Digital Integration of Economic Systems While Ensuring Food Security','Finite Element Analysis of Electric Power Distribution Pole Geometries','Feature Alignment for Image Classification'])assert.equal(assessRelevance({...ai,title}).included,false,title);});
test('retains safety-adjacent topics across modalities and general cybersecurity',()=>{for(const title of ['Multimodal Prompt Injection Attacks','Hallucination Detection in Language Models','Fairness in Personalized Recommenders','Deepfake Audio Detection with Neural Networks','Mechanistic Interpretability of LLMs','Privacy-preserving Federated Learning','Robustness of Vision Models under Distribution Shift','Malware Detection without Machine Learning','Post-Quantum Cryptography','Content Moderation with Foundation Models'])assert.equal(assessRelevance({...ai,title}).included,true,title);});
test('security categories and venues provide evidence without requiring AI terms',()=>{assert.equal(assessRelevance({title:'Secure Traffic Analysis',categories:['cs.CR']}).included,true);assert.equal(assessRelevance({title:'Protocol analysis',venue:'USENIX Security',publicationType:'conference'}).included,true);assert.equal(assessRelevance({title:'How Real is Your Jailbreak?',venue:'ACL',publicationType:'conference'}).included,true);assert.equal(assessRelevance({title:'Generic Agent Benchmark',venue:'ACL',publicationType:'conference'}).included,false);});
test('rechecks cached records instead of trusting old tags or acceptance flags',()=>{const rows=filterRelevantPapers([{title:'Food Security',topics:['Privacy & security'],relevance:{included:true}},{title:'Prompt Injection in LLMs',categories:['cs.CL']}]);assert.equal(rows.length,1);assert(rows[0].relevance.reasons.length);});
test('arXiv ingestion enforces admission before topics enter the UI',()=>{const xml='<feed>'+['A Generic Agent Benchmark','Prompt Injection in LLMs'].map((t,i)=>`<entry><id>https://arxiv.org/abs/2609.0000${i}</id><title>${t}</title><summary>Research</summary><author><name>A</name></author><category term="cs.AI"/><published>2026-09-01</published></entry>`).join('')+'</feed>';assert.equal(parseFeed(xml).length,1);});
test('embeds source figures only after title and image-host checks',()=>{const html='<h1 class="ltx_title_document">Safe Agents</h1><figure class="ltx_figure"><img src="2609.00001v1/x1.png"><figcaption>Figure 1: Architecture overview.</figcaption></figure><figure class="ltx_figure"><img src="https://evil.example/x.png"><figcaption>Figure 2: Diagram</figcaption></figure>';const figures=parsePaperFigures(html,{title:'Safe Agents'},'https://arxiv.org/html/2609.00001');assert.equal(figures.length,1);assert.equal(figures[0].url,'https://arxiv.org/html/2609.00001v1/x1.png');assert.deepEqual(parsePaperFigures(html,{title:'Other paper'},'https://arxiv.org/html/2609.00001'),[]);});
