import test from 'node:test';import assert from 'node:assert/strict';
import {parsePaperAffiliations} from './affiliations.js';import {withAffiliations,normalizeGroups} from './shared/affiliations.js';import {parseBlogFeed,parseBlogPage,blogLinks} from './blogs.js';
const source={name:'Example Lab',id:'lab',institution:'Example',url:'https://lab.example/blog/',path:'^/blog/[^/]+/?$'};
test('extracts only explicit paper affiliations, removes markers and emails, and checks title',()=>{const html='<h1 class="ltx_title_document">Safe Agents</h1><div class="ltx_authors"><div class="ltx_role_affiliation"><span class="ltx_contact_name">Affiliation:</span><sup>1</sup>Yale University<br>contact@yale.edu<br><sup>2</sup>Google DeepMind</div></div><p>Related work: Stanford University</p>';assert.deepEqual(parsePaperAffiliations(html,{title:'Safe Agents'}),['Yale University','Google DeepMind']);assert.deepEqual(parsePaperAffiliations(html,{title:'Different paper'}),[]);});
test('uses direct paper evidence in preference to index labels without replacing known names with empty results',()=>{assert.deepEqual(withAffiliations({groups:['Known Lab']},{groups:[],groupStatus:'error'}).groups,['Known Lab']);assert.deepEqual(withAffiliations({groups:['Wrong Lab']},{groups:['Paper Lab'],groupOrigin:'paper'}).groups,['Paper Lab']);assert.deepEqual(normalizeGroups(['Joint Research Centre','Joint Research Center','MIT','MIT']),['Joint Research Centre','MIT']);});
test('RSS filters safety topics, rejects external URLs and future dates, uses configured publisher',()=>{const xml='<rss><channel>'+[['AI safety','https://lab.example/blog/safe','2026-09-01'],['New GPU pricing','https://lab.example/blog/product','2026-09-01'],['Alignment','https://evil.example/x','2026-09-01'],['Alignment tomorrow','https://lab.example/blog/future','2027-01-01']].map(([t,u,d])=>`<item><title>${t}</title><link>${u}</link><pubDate>${d}</pubDate><author>Person</author></item>`).join('')+'</channel></rss>';const rows=parseBlogFeed(xml,source,Date.parse('2026-09-10'));assert.equal(rows.length,1);assert.equal(rows[0].kind,'blog');assert.equal(rows[0].institution,'Example');assert.deepEqual(rows[0].authors,['Person']);});
test('Atom supports alternate links and preserves unknown dates',()=>{const rows=parseBlogFeed('<feed><entry><title>Alignment monitoring</title><link rel="alternate" href="https://lab.example/blog/alignment"/><summary>Safe AI</summary><author><name>Ada</name></author></entry></feed>',source);assert.equal(rows[0].published,null);assert.equal(rows[0].abstract,'Safe AI');assert.deepEqual(rows[0].authors,['Ada']);});
test('HTML index deduplicates links and article parser never uses crawl time as publication',()=>{const links=blogLinks('<a href="/blog/safe">AI safety Sep 1, 2026</a><a href="/blog/safe">Read</a><a href="https://evil.example/blog/a">x</a>',source);assert.equal(links.length,1);const html='<h1>AI safety</h1><meta name="description" content="Alignment methods">';assert.equal(parseBlogPage(html,source,links[0]).published,'2026-09-01T00:00:00.000Z');assert.equal(parseBlogPage(html,source,{url:links[0].url}).published,null);assert.equal(parseBlogPage(html+'<p>August 2026</p>',source,{url:links[0].url}).datePrecision,'month');});

test('keeps wrapped institution names together and discards contribution notes',()=>{const html='<h1 class="ltx_title_document">Safe AI</h1><div class="ltx_authors"><div class="ltx_role_affiliation">Florida International<br>University (FIU),<br>Miami, FL, USA</div><div class="ltx_role_affiliation">Brown University<span class="ltx_note">Equal contribution</span></div></div>';assert.deepEqual(parsePaperAffiliations(html,{title:'Safe AI'}),['Florida International University (FIU), Miami, FL, USA','Brown University']);});
