const holidayKeys = new Set(['2026-01-01','2026-01-19','2026-02-16','2026-05-25','2026-06-19','2026-07-03','2026-09-07','2026-10-12','2026-11-11','2026-11-26','2026-12-25']);
const originalText = new Map(Array.from(document.querySelectorAll('[data-i18n]'), node => [node, node.innerHTML]));
const korean = {
  topLabel:'H-1B 진행 현황', home:'홈으로 ↗', eyebrow:'내 H-1B 진행 상황 / 네브래스카', headline:'H-1B <em>승인을 기다리는 중입니다.</em>',
  intro:'USCIS의 프리미엄 프로세싱 접수일은 2026년 9월 22일이고, 접수 통지서 날짜는 9월 25일입니다. 예정된 근무 시작일은 <strong>10월 12일</strong>입니다.',
  targetLabel:'근무 시작 목표일', oct:'10월', day12:'12일', year2026:'2026년', targetText:'10월 12일 근무 시작을 계획하고 있습니다. 그날은 연방 공휴일이어서 직전 영업일은 10월 9일입니다.',
  clockLabel:'프리미엄 심사 기한', oct14:'10월 14일', day15label:'15영업일째(예상)', clockText:'9월 22일 접수 후 다음 날인 9월 23일을 첫날로 계산했습니다. 주말과 10월 12일 연방 공휴일은 제외했습니다. 정확한 프리미엄 심사 시작일은 통지서나 담당 변호사를 통해 확인해야 합니다.', receivedShort:'9월 22일 · 접수',
  forecastKicker:'공개 사례를 바탕으로 한 예상', forecastHeadline:'최근 사례를 비교하고 있습니다…', forecastText:'승인 사례를 비교한 수치이며 전체 접수 건을 대표하지는 않습니다.',
  caseKicker:'01 / 내 신청', timelineTitle:'내 접수 일정', nebraskaPremium:'네브래스카 · 프리미엄', sep22:'9월 22일', receivedTitle:'USCIS 접수', receivedDescription:'프리미엄 프로세싱 접수일', sep25:'9월 25일', noticeTitle:'접수 통지서 발행', noticeDescription:'통지서에 적힌 날짜', oct12:'10월 12일', startTitle:'예정된 근무 시작일', startDescription:'근무 시작 목표일 · 연방 공휴일', actionTitle:'프리미엄 심사 15영업일째(예상)', actionDescription:'승인, 거절, 추가서류 요청(RFE) 등의 조치가 있을 수 있음', clockCaveat:'접수일과 통지서 날짜는 다릅니다. 실제 프리미엄 심사 시작일이 9월 25일이라면 15영업일째는 10월 14일이 아닌 10월 19일입니다. I-907 통지서나 담당 변호사에게 시작일을 확인하세요.',
  interpretKicker:'02 / 해석', interpretTitle:'사례를 어떻게 봐야 할까?', oct6:'10월 6일', oct9:'10월 9일', windowLead:'승인 소식을 주의 깊게 확인할 기간입니다. 승인 예정일은 아닙니다.', windowText:'분석에 포함된 것은 승인을 받았다고 글을 올린 사람들의 사례입니다. 모든 접수 건을 포함하지 않으므로 10월 12일까지 승인될 확률은 계산할 수 없습니다. 담당 변호사가 승인 이메일을 먼저 받고 USCIS 온라인 조회 결과는 나중에 바뀔 수도 있습니다.', workNote:'10월 12일 근무를 시작하려면 어떤 승인 서류가 필요한지 고용주와 담당 변호사에게 확인하세요. 공휴일 전 마지막 영업일은 10월 9일입니다.',
  patternsKicker:'03 / 분석 자료', patternsTitle:'승인까지 실제로 며칠 걸렸을까?', analysisIntro:'2026년 네브래스카 프리미엄 프로세싱 사례 중 접수일 또는 프리미엄 심사 시작일과 승인일을 모두 확인할 수 있는 게시물 24건을 모았습니다. 시작일 다음 날부터 주말과 연방 공휴일을 제외해 영업일을 계산했습니다. 각 사례의 원문을 아래에서 볼 수 있습니다.', medianMetric:'전체 승인 사례의 중앙값(영업일)', conditionalMetric:'8영업일이 지난 뒤 승인된 사례의 중앙값', recentMetric:'8월 20일 이후 시작된 사례의 중앙값', chartTitle:'승인까지 걸린 영업일', chartNote:'아래 막대는 수집한 승인 사례의 건수입니다. 승인 확률을 나타내지 않습니다.', early:'짧게 걸림', later:'오래 걸림', findingsTitle:'사례에서 보이는 점', finding1:'전체 24건의 중앙값은 10영업일입니다. 9월 22일을 기준으로 하면 10월 6일입니다.', finding2:'8월 20일 이후 시작된 승인 사례 12건의 중앙값은 8영업일입니다. 이번 접수일 기준으로는 10월 2일입니다.', finding3:'8영업일이 지난 뒤 승인된 사례 13건의 중앙값은 11영업일, 이번 접수일 기준 10월 7일입니다. 개인의 승인 확률을 뜻하지는 않습니다.', finding4:'9월 25일이라는 통지서 날짜만으로는 USCIS 내부 심사 단계나 승인일을 알 수 없습니다.', recordsTitle:'사례별 원문', recordsNote:'신청 유형을 고르면 해당 사례만 볼 수 있습니다. ‘미확인’은 게시물에 유형이 적혀 있지 않다는 뜻입니다. 각 행의 ‘계산에 사용한 기준’을 확인하세요. Receipt라는 표현만으로 USCIS received 날짜와 통지서 날짜를 구별할 수 없는 경우도 있습니다.', thType:'유형', thStart:'계산 시작일', thBasis:'계산에 사용한 기준', thApproved:'승인일', thDays:'영업일', thSource:'원문', methodNote:'분석의 한계: Reddit 게시물은 작성자의 자기 보고입니다. 결과가 나온 사람이 글을 더 많이 올릴 수 있고, 정확한 프리미엄 심사 시작일이나 신청 사정도 확인할 수 없습니다. 이 사례들은 전체 접수 건을 대표하지 않으며 승인율을 추정하는 데 사용할 수 없습니다.',
  lateKicker:'04 / 오래 걸린 사례', lateTitle:'더 오래 기다렸다는 글도 있습니다', lateText:'아래 게시물에서는 마지막으로 확인된 시점까지 승인이 보고되지 않았습니다. 승인일까지의 기간을 보여주는 그래프에는 넣지 않았지만, 예상 날짜의 불확실성을 보여줍니다. 이후 승인 여부나 RFE, 실제 심사 시작일은 확인되지 않을 수 있습니다.',
  liveKicker:'05 / 최근 게시물', liveTitle:'최근 관련 게시물', liveDescription:'페이지를 열어 둔 동안 공개 피드를 15초마다 확인합니다. Reddit 공개 RSS와 검색 결과를 모으는 작업은 5분 간격으로 예약되어 있지만, 접근 제한이나 GitHub 실행 지연이 있을 수 있습니다. USCIS나 Reddit의 게시 직후 반영을 보장하지는 않습니다.', checkNow:'지금 확인 ↻',
  sourcesKicker:'06 / 공식 자료', sourcesTitle:'날짜 계산에 사용한 자료', uscisLink:'USCIS 프리미엄 프로세싱 ↗', holidaysLink:'2026년 연방 공휴일 ↗', statusLink:'USCIS 케이스 상태 조회 ↗', footerLeft:'개인 일정 · 2026년 10월 2일까지 자료 검토', footerRight:'공개 게시물은 참고 사례입니다. 실제 진행 상황은 USCIS와 담당 변호사에게 확인하세요.'
};
const typeLabels = {
  en:{all:'All',coe:'Transfer',extension:'Extension',cos:'Change of status',initial:'Initial',amendment:'Amendment',unknown:'Unknown'},
  ko:{all:'전체',coe:'고용주 변경',extension:'연장',cos:'신분 변경',initial:'신규',amendment:'변경 신청',unknown:'미확인'}
};
const basisLabels={
  en:{receipt:'Reported receipt date','premium receipt':'Reported PP receipt date','premium clock':'PP clock start','I-907 received':'USCIS received I-907','premium date unclear':'PP date — meaning unclear'},
  ko:{receipt:'게시물의 receipt 날짜','premium receipt':'게시물의 PP receipt 날짜','premium clock':'프리미엄 심사 시작일','I-907 received':'USCIS I-907 접수일','premium date unclear':'PP 날짜 — 의미 불명확'}
};
const basisCaveat={en:'Mixed date bases: the statistics, chart and forecast combine reported receipt dates, PP clock starts and other PP dates. They are not a received-only comparison. Business days are counted after each row’s calculation start date; notice dates are not substituted for received dates.',ko:'기준 혼합: 통계·그래프·예상 날짜는 게시물의 receipt 날짜, PP 시작일 및 기타 PP 날짜를 함께 사용합니다. USCIS received 기준으로만 비교한 결과가 아닙니다. 영업일은 각 행의 계산 시작일 다음 날부터 세며, 통지서 날짜를 received 날짜로 대신 넣지 않습니다.'};
let language=localStorage.getItem('h1b-language')||((navigator.language||'').toLowerCase().startsWith('ko')?'ko':'en');
let caseData=null, activeFilter='all', feedItems=[], feedChangedAt=null, checking=false, lastSignature='';

function easternKey(date) {
  const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);
  const p=Object.fromEntries(parts.map(part=>[part.type,part.value]));
  return `${p.year}-${p.month}-${p.day}`;
}
function utcDay(key){return new Date(`${key}T12:00:00Z`);}
function businessDays(start,end){let count=0;const stop=utcDay(end);for(let day=utcDay(start);day<stop;){day.setUTCDate(day.getUTCDate()+1);const key=day.toISOString().slice(0,10);if(day.getUTCDay()!==0&&day.getUTCDay()!==6&&!holidayKeys.has(key))count++;}return count;}
function dateForBusinessDay(start,number){const day=utcDay(start);let count=0;while(count<number){day.setUTCDate(day.getUTCDate()+1);const key=day.toISOString().slice(0,10);if(day.getUTCDay()!==0&&day.getUTCDay()!==6&&!holidayKeys.has(key))count++;}return day.toISOString().slice(0,10);}
function daysBetween(start,end){return Math.round((utcDay(end)-utcDay(start))/86400000);}
function median(values){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);const m=sorted.length/2;return sorted.length%2?sorted[Math.floor(m)]:(sorted[m-1]+sorted[m])/2;}
function formatNumber(value){return value==null?'—':new Intl.NumberFormat(language==='ko'?'ko-KR':'en-US',{maximumFractionDigits:1}).format(value);}
function displayDate(key){return new Intl.DateTimeFormat(language==='ko'?'ko-KR':'en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(utcDay(key));}
function safeLink(value){try{const url=new URL(value);return url.protocol==='https:'&&['news.google.com','www.reddit.com','reddit.com'].includes(url.hostname)?url.href:null;}catch{return null;}}

function updateClock(){const now=new Date();const remaining=daysBetween(easternKey(now),'2026-10-12');document.getElementById('target-countdown').textContent=language==='ko'?(remaining>0?`근무 시작 예정일까지 ${remaining}일 남았습니다`:remaining===0?'오늘이 예정된 근무 시작일입니다':`예정된 근무 시작일이 ${Math.abs(remaining)}일 지났습니다`):(remaining>1?`${remaining} calendar days until planned start`:remaining===1?'Tomorrow is the planned start':remaining===0?'Planned start date is today':`${Math.abs(remaining)} calendar day${Math.abs(remaining)===1?'':'s'} past planned start`);const count=businessDays('2026-09-22',easternKey(now));document.getElementById('business-day').textContent=language==='ko'?`15영업일 중 ${Math.min(count,15)}영업일 경과`:`Day ${Math.min(count,15)} of 15`;document.getElementById('clock-progress').style.width=`${Math.min(100,count/15*100)}%`;renderForecast();}

function renderForecast(){if(!caseData)return;const today=easternKey(new Date());const elapsed=businessDays('2026-09-22',today);const approved=caseData.cases.map(item=>businessDays(item.start,item.approved));const comparable=approved.filter(days=>days>elapsed);const title=document.getElementById('insight-title');const description=document.querySelector('[data-i18n="forecastText"]');if(elapsed>=15||!comparable.length){title.textContent=language==='ko'?'기존 사례만으로는 다음 날짜를 예측하기 어렵습니다.':'Past reports no longer give a useful date estimate.';description.textContent=language==='ko'?'실제 프리미엄 심사 시작일과 USCIS 조치 여부를 통지서 또는 담당 변호사에게 확인하세요.':'Confirm the actual premium clock start and any USCIS action with the notice or your attorney.';return;}const midpoint=median(comparable);const predicted=displayDate(dateForBusinessDay('2026-09-22',Math.round(midpoint)));const todayLabel=displayDate(today);const emphasis=document.createElement('span');emphasis.textContent=predicted+(language==='ko'?'입니다.':'.');title.replaceChildren(document.createTextNode(language==='ko'?`${todayLabel}에도 심사 중이라면, 승인 사례의 중간 시점은 `:`If still pending on ${todayLabel}, comparable approvals center on `),emphasis);description.textContent=language==='ko'?`내 9월 22일 접수일 기준 ${elapsed}영업일이 경과했습니다. 각 사례의 계산 시작일부터 이보다 오래 걸려 승인된 공개 사례 ${comparable.length}건의 중앙값은 ${formatNumber(midpoint)}영업일입니다. 실제 심사 시작일이 9월 22일과 다르면 날짜도 달라집니다. 비교 표본에는 receipt 날짜와 PP 시작일 등 서로 다른 기준이 섞여 있습니다. 승인 가능성이나 USCIS의 내부 단계를 나타내지는 않습니다.`:`Among ${comparable.length} published approvals that took longer than day ${elapsed}, the median was business day ${formatNumber(midpoint)}. This assumes the premium clock began September 22; a different clock start shifts the date. The sample mixes receipt dates, PP clock starts and other PP dates; it is not received-only. It does not estimate approval probability or reveal USCIS's internal stage.`;}

function setLanguage(next){language=next;localStorage.setItem('h1b-language',next);document.documentElement.lang=next;document.title=next==='ko'?'H-1B 진행 현황 · 네브래스카 프리미엄 프로세싱':'H-1B timeline · Nebraska premium processing';for(const [node,english] of originalText){node.innerHTML=next==='ko'?(korean[node.dataset.i18n]||english):english;}for(const button of document.querySelectorAll('[data-language]')){const selected=button.dataset.language===next;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected));}updateClock();renderAnalysis();renderFeed(feedItems);updateFeedStatus();}

function renderAnalysis(){if(!caseData)return;const all=caseData.cases.map(item=>({...item,days:businessDays(item.start,item.approved)}));const days=all.map(item=>item.days);document.getElementById('sample-size').textContent=language==='ko'?`승인 사례 ${all.length}건`:`${all.length} approved reports`;document.getElementById('metric-median').textContent=formatNumber(median(days));document.getElementById('metric-pending').textContent=formatNumber(median(days.filter(day=>day>8)));document.getElementById('metric-september').textContent=formatNumber(median(all.filter(item=>item.start>='2026-08-20').map(item=>item.days)));renderForecast();
  document.getElementById('basis-explanation').textContent=basisCaveat[language];
  const filters=document.getElementById('case-filters');filters.replaceChildren();for(const type of ['all','coe','extension','cos','initial','amendment','unknown']){const button=document.createElement('button');button.type='button';button.textContent=typeLabels[language][type];button.className=activeFilter===type?'selected':'';button.setAttribute('aria-pressed',String(activeFilter===type));button.addEventListener('click',()=>{activeFilter=type;renderAnalysis();});filters.append(button);}
  const filtered=activeFilter==='all'?all:all.filter(item=>item.type===activeFilter);renderHistogram(filtered);
  let summary=document.getElementById('filter-summary');if(!summary){summary=document.createElement('p');summary.id='filter-summary';summary.className='filter-summary';document.querySelector('.table-heading').after(summary);}
  const values=filtered.map(item=>item.days);summary.textContent=language==='ko'?`${typeLabels.ko[activeFilter]} · 승인 사례 ${values.length}건 · 중앙값 ${formatNumber(median(values))}영업일 · 범위 ${Math.min(...values)}~${Math.max(...values)}영업일${values.length<3?' · 사례가 너무 적어 경향을 판단하기 어렵습니다.':''}`:`${typeLabels.en[activeFilter]}: ${values.length} approved reports · median ${formatNumber(median(values))} business days · range ${Math.min(...values)}–${Math.max(...values)} days${values.length<3?' · Too few reports to infer a pattern.':''}`;
  const body=document.getElementById('cases-body');body.replaceChildren();for(const item of [...filtered].sort((a,b)=>b.approved.localeCompare(a.approved))){const row=document.createElement('tr');const type=document.createElement('td');type.textContent=typeLabels[language][item.type];row.append(type);const start=document.createElement('td');start.textContent=displayDate(item.start);row.append(start);const basis=document.createElement('td');basis.className='basis-cell';const label=document.createElement('strong');label.textContent=basisLabels[language][item.basis]||item.basis;basis.append(label);const note=item.basisNote?.[language];if(note){const detail=document.createElement('small');detail.className='basis-note';detail.textContent=note;basis.append(detail);}row.append(basis);for(const value of [displayDate(item.approved),String(item.days)]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}const source=document.createElement('td');const a=document.createElement('a');a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=language==='ko'?'원문 ↗':'Post ↗';a.setAttribute('aria-label',(language==='ko'?'원문 열기: ':'Open source post: ')+displayDate(item.start)+' '+displayDate(item.approved));source.append(a);row.append(source);body.append(row);}
  const pending=document.getElementById('pending-list');pending.replaceChildren();for(const item of caseData.pendingExamples){const a=document.createElement('a');a.className='pending-item';a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=(language==='ko'?item.labelKo:item.label)+' ↗';pending.append(a);}}
function renderHistogram(items){const counts=new Map();for(const item of items)counts.set(item.days,(counts.get(item.days)||0)+1);const max=Math.max(1,...counts.values());const chart=document.getElementById('histogram');chart.replaceChildren();for(let day=4;day<=15;day++){const count=counts.get(day)||0;const column=document.createElement('div');column.className='hist-column';column.setAttribute('aria-label',language==='ko'?`${day}영업일: ${count}건`:`Day ${day}: ${count} reports`);const number=document.createElement('span');number.className='hist-count';number.textContent=count||'';const bar=document.createElement('span');bar.className='hist-bar';bar.style.height=`${Math.max(3,count/max*108)}px`;if(!count)bar.classList.add('empty');const label=document.createElement('small');label.textContent=day;column.append(number,bar,label);chart.append(column);}chart.setAttribute('aria-label',language==='ko'?'영업일별 승인 보고 건수 그래프':'Histogram of reported approvals by business day');}

function renderFeed(items){const list=document.getElementById('feed-list');list.replaceChildren();if(!items.length){const empty=document.createElement('p');empty.className='feed-empty';empty.textContent=language==='ko'?'최근 공개 피드에서 관련 게시물을 찾지 못했습니다. 위의 사례별 원문도 확인해 보세요.':'No recent matching posts appeared in the public feed. Check the source records above.';list.append(empty);return;}for(const item of items.slice(0,8)){const link=safeLink(item.link);if(!link)continue;const a=document.createElement('a');a.className='feed-item';a.href=link;a.target='_blank';a.rel='noopener noreferrer';const title=document.createElement('span');title.className='feed-title';title.textContent=item.title.replace(/ - Reddit$/i,'');const date=document.createElement('time');date.className='feed-date';date.dateTime=item.date.toISOString();date.textContent=new Intl.DateTimeFormat(language==='ko'?'ko-KR':'en-US',{month:'short',day:'numeric',timeZone:'America/New_York'}).format(item.date)+' · '+(language==='ko'?(item.source==='reddit'?'Reddit':'검색 색인'):(item.source==='reddit'?'Reddit':'Indexed'))+' ↗';a.append(title,date);list.append(a);}}
function updateFeedStatus(){const changed=document.getElementById('feed-updated');changed.textContent=feedChangedAt?(language==='ko'?'목록 마지막 변경: ':'List last changed ')+new Intl.DateTimeFormat(language==='ko'?'ko-KR':'en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'}).format(feedChangedAt)+' ET':(language==='ko'?'목록 변경 시각을 확인할 수 없습니다':'List update time unavailable');const state=document.getElementById('feed-state');if(state.dataset.error==='true'){state.textContent=language==='ko'?'새 게시물을 불러오지 못했습니다':'Feed temporarily unavailable';return;}state.textContent=checking?(language==='ko'?'확인 중…':'Checking…'):(language==='ko'?`공개 게시물 ${feedItems.length}건`:`${feedItems.length} public posts`);}
async function checkFeed(){if(checking||document.hidden)return;checking=true;updateFeedStatus();try{const source=location.hostname==='jrohsc.github.io'?'https://raw.githubusercontent.com/jrohsc/jrohsc.github.io/master/h1b-monitoring/feed.json':'feed.json';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),11000);let response;try{response=await fetch(source+'?check='+Date.now(),{signal:controller.signal,cache:'no-store'});}finally{clearTimeout(timer);}if(!response.ok)throw new Error('Feed unavailable');const data=await response.json();if(!Array.isArray(data.items))throw new Error('Invalid feed');const items=data.items.map(item=>({title:item.title||'',link:item.link||'',date:new Date(item.date||0),source:item.source==='reddit'?'reddit':'indexed'})).filter(item=>item.title&&Number.isFinite(item.date.getTime())).sort((a,b)=>b.date-a.date);const signature=items.map(item=>item.link).join('|');feedItems=items;const changedAt=new Date(data.updatedAt||0);feedChangedAt=Number.isFinite(changedAt.getTime())?changedAt:null;if(signature!==lastSignature){renderFeed(feedItems);lastSignature=signature;}document.getElementById('feed-state').dataset.error='false';document.getElementById('last-check').textContent=(language==='ko'?'마지막 확인: ':'Last checked ')+new Intl.DateTimeFormat(language==='ko'?'ko-KR':'en-US',{hour:'numeric',minute:'2-digit',second:'2-digit',timeZone:'America/New_York'}).format(new Date())+' ET';}catch{document.getElementById('feed-state').dataset.error='true';document.getElementById('last-check').textContent=language==='ko'?'이전에 불러온 결과를 표시하고 있습니다. 잠시 후 다시 시도해 주세요.':'Showing last available results; try again shortly';if(!lastSignature){const list=document.getElementById('feed-list');list.replaceChildren();const p=document.createElement('p');p.className='feed-empty';p.textContent=language==='ko'?'지금은 새 게시물을 불러올 수 없습니다. 위의 사례별 원문은 계속 볼 수 있습니다.':'Could not load the public-post feed. The source records above remain available.';list.append(p);}}finally{checking=false;updateFeedStatus();}}

for(const button of document.querySelectorAll('[data-language]'))button.addEventListener('click',()=>setLanguage(button.dataset.language));document.getElementById('refresh-feed').addEventListener('click',checkFeed);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkFeed();});
fetch('cases.json').then(response=>{if(!response.ok)throw new Error('Missing case data');return response.json();}).then(data=>{caseData=data;renderAnalysis();}).catch(()=>{document.getElementById('analysis-title').textContent=language==='ko'?'사례 데이터를 불러올 수 없습니다':'Case data unavailable';});
setLanguage(language);checkFeed();setInterval(checkFeed,15000);setInterval(updateClock,60000);
