// Run against a local preview. No applications or external messages are submitted.
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
const executablePath = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch({ headless: true, ...(existsSync(executablePath) ? { executablePath } : {}) });
const origin = process.env.RADAR_TEST_URL || 'http://localhost:8766/ai-jobs/';
const context = await browser.newContext({ viewport: { width: 1440, height: 1080 } });
const page = await context.newPage(), errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto(origin); await page.locator('.job-card').first().waitFor();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
const first = page.locator('.job-card').first(), title = await first.locator('.job-title').textContent();
const firstID = await first.getAttribute('data-id');
assert.ok((await first.locator('.apply').getAttribute('href')).startsWith('https://'));
assert.equal(await first.locator('.apply').getAttribute('rel'), 'noopener noreferrer');
await first.locator('.save').click();
await page.locator('[data-view="saved"]').click();
assert.equal(await page.locator('.job-card').count(), 1);
await page.reload(); await page.locator('.job-card').first().waitFor();
await page.locator('[data-view="saved"]').click();
assert.equal(await page.locator('.job-title').first().textContent(), title);
await page.locator('.status-select').first().selectOption('Applied');
await page.locator('[data-view="applied"]').click();
assert.equal(await page.locator('.job-card').count(), 1);
await page.locator('.job-title').first().click();
assert.equal(await page.locator('dialog').isVisible(), true);
assert.match(await page.locator('#detail-content').textContent(), /Why this role is here/);
await page.keyboard.press('Escape');
assert.equal(await page.locator('dialog').isVisible(), false);
await page.locator('[data-view="all"]').click();
await page.locator('#type').selectOption('Internship');
assert.ok(await page.locator('.job-card').count() > 0);
assert.ok((await page.locator('.job-meta').allTextContents()).every(t => t.includes('Internship')));
await page.locator('#reset').click();
await page.locator('#search').fill('definitely-no-such-job-zz987654');
assert.equal(await page.locator('.job-card').count(), 0);
assert.match(await page.locator('.empty').textContent(), /No matching opportunities/);
await page.locator('#empty-reset').click();
await page.locator('#bigtech').check();
assert.equal(await page.locator('.priority-badge').count(), await page.locator('.job-card').count());
await page.locator('#reset').click();
await page.locator('[data-topic="Audio"]').click();
assert.ok((await page.locator('.job-tags').allTextContents()).every(t => t.includes('Audio')));
await page.locator('#reset').click();
await page.locator('#load-more').click();
assert.equal(await page.locator('.job-card').count(), 80);
await page.locator('[data-view="sources"]').click();
assert.equal(await page.locator('.source-card').count(), 20);
assert.ok(await page.locator('.source-status.manual').count() >= 2);
const downloadPromise = page.waitForEvent('download');
await page.locator('#export').click();
const download = await downloadPromise;
assert.equal(download.suggestedFilename(), 'ai-radar-tracker.json');
await page.locator('[data-view="all"]').click();
await page.evaluate(() => scrollTo(0, 0));
await page.screenshot({ path: '/tmp/ai-jobs-desktop.png' });
await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(() => scrollTo(0, 0));
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.screenshot({ path: '/tmp/ai-jobs-mobile.png' });
await page.locator('.job-title').first().click();
assert.equal(await page.locator('dialog').isVisible(), true);
await page.keyboard.press('Escape');
assert.deepEqual(errors, []);
// A new browser session cannot inherit another browser's application states.
const cleanContext = await browser.newContext(); const clean = await cleanContext.newPage();
await clean.goto(origin); await clean.locator('.job-card').first().waitFor();
assert.equal(await clean.locator('#nav-applied').textContent(), '0');
// Feed failures must expose a retry instead of silently showing an empty job market.
await clean.route('**/data.json*', route => route.fulfill({ status: 503, body: 'unavailable' }));
await clean.reload(); await clean.locator('#retry').waitFor();
assert.match(await clean.locator('#notice').textContent(), /Could not load/);
console.log('PASS: desktop/mobile layout, filtering, save/reload, application tracking, detail dialog, source coverage, export, local-only state, and feed failure.');
await browser.close();
