export const sources = [
  { id: 'google', name: 'Google & DeepMind', tier: 1, adapter: 'google', url: 'https://www.google.com/about/careers/applications/jobs/results/?location=United%20States', queries: ['AI safety', 'AI security', 'privacy', 'audio', 'speech', 'multimodal', 'student researcher', 'research intern', 'PhD intern'] },
  { id: 'apple', name: 'Apple', tier: 1, adapter: 'apple', url: 'https://jobs.apple.com/en-us/search?location=united-states-USA', queries: ['safety', 'security', 'privacy', 'audio', 'speech', 'multimodal', 'machine learning internship', 'research', 'PhD internship'] },
  { id: 'microsoft', name: 'Microsoft', tier: 1, adapter: 'eightfold', domain: 'microsoft.com', url: 'https://apply.careers.microsoft.com/careers', queries: ['research intern', 'internship', 'research'], note: 'Official Microsoft Careers, including Microsoft Research and applied science teams.' },
  { id: 'amazon', name: 'Amazon', tier: 1, adapter: 'amazon', url: 'https://www.amazon.jobs/en/search?base_query=AI&loc_query=United+States', queries: ['AI safety', 'AI security', 'privacy machine learning', 'audio', 'speech', 'multimodal', 'applied scientist intern', 'research intern', 'PhD intern'] },
  { id: 'nvidia', name: 'NVIDIA', tier: 1, adapter: 'workday', tenant: 'nvidia', host: 'nvidia.wd5.myworkdayjobs.com', board: 'NVIDIAExternalCareerSite', url: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite', queries: ['safety', 'security', 'privacy', 'audio', 'speech', 'multimodal', 'research intern', 'PhD intern'] },
  { id: 'meta', name: 'Meta', tier: 1, adapter: 'meta', url: 'https://www.metacareers.com/jobsearch/?q=research%20intern' },
  { id: 'adobe', name: 'Adobe', tier: 1, adapter: 'workday', tenant: 'adobe', host: 'adobe.wd5.myworkdayjobs.com', board: 'external_experienced', url: 'https://adobe.wd5.myworkdayjobs.com/external_experienced', queries: ['research', 'audio', 'multimodal', 'AI safety', 'privacy', 'intern'] },
  { id: 'qualcomm', name: 'Qualcomm', tier: 1, adapter: 'eightfold', domain: 'qualcomm.com', url: 'https://careers.qualcomm.com/careers', queries: ['internship', 'intern', 'research'] },
  { id: 'openai', name: 'OpenAI', tier: 2, adapter: 'ashby', board: 'openai', url: 'https://openai.com/careers/search/' },
  { id: 'anthropic', name: 'Anthropic', tier: 2, adapter: 'greenhouse', board: 'anthropic', url: 'https://www.anthropic.com/careers/jobs' },
  { id: 'scale', name: 'Scale AI', tier: 2, adapter: 'greenhouse', board: 'scaleai', url: 'https://www.scale.com/careers' },
  { id: 'together', name: 'Together AI', tier: 2, adapter: 'greenhouse', board: 'togetherai', url: 'https://www.together.ai/careers' },
  { id: 'xai', name: 'xAI', tier: 2, adapter: 'greenhouse', board: 'xai', url: 'https://x.ai/careers' },
  { id: 'cohere', name: 'Cohere', tier: 2, adapter: 'ashby', board: 'cohere', url: 'https://jobs.ashbyhq.com/cohere' },
  { id: 'mistral', name: 'Mistral AI', tier: 2, adapter: 'ashby', board: 'mistral.ai', url: 'https://jobs.ashbyhq.com/mistral.ai' },
  { id: 'dolby', name: 'Dolby', tier: 3, adapter: 'dolby', url: 'https://careers.dolby.com/search/', note: 'US roles from the official Dolby careers board.' },
  { id: 'elevenlabs', name: 'ElevenLabs', tier: 3, adapter: 'ashby', board: 'elevenlabs', url: 'https://jobs.ashbyhq.com/elevenlabs' },
  { id: 'suno', name: 'Suno', tier: 3, adapter: 'ashby', board: 'suno', url: 'https://jobs.ashbyhq.com/suno' },
  { id: 'hume', name: 'Hume AI', tier: 3, adapter: 'ashby', board: 'hume-ai', url: 'https://jobs.ashbyhq.com/hume-ai' },
  { id: 'sesame', name: 'Sesame', tier: 3, adapter: 'ashby', board: 'sesame', url: 'https://jobs.ashbyhq.com/sesame' },
  { id: 'brave', name: 'Brave', tier: 3, adapter: 'greenhouse', board: 'brave', url: 'https://brave.com/careers/' },
];
