export const sources = [
  { id: 'google', name: 'Google & DeepMind', tier: 1, adapter: 'google', url: 'https://www.google.com/about/careers/applications/jobs/results/?location=United%20States', queries: ['AI safety', 'AI security', 'privacy', 'audio', 'speech', 'multimodal', 'student researcher'] },
  { id: 'apple', name: 'Apple', tier: 1, adapter: 'apple', url: 'https://jobs.apple.com/en-us/search?location=united-states-USA', queries: ['safety', 'security', 'privacy', 'audio', 'speech', 'multimodal', 'machine learning internship'] },
  { id: 'microsoft', name: 'Microsoft Research', tier: 1, adapter: 'msr', url: 'https://www.microsoft.com/en-us/research/careers/open-positions/', note: 'Microsoft Research board only; additional Microsoft teams may have other openings.' },
  { id: 'amazon', name: 'Amazon', tier: 1, adapter: 'amazon', url: 'https://www.amazon.jobs/en/search?base_query=AI&loc_query=United+States', queries: ['AI safety', 'AI security', 'privacy machine learning', 'audio', 'speech', 'multimodal', 'applied scientist intern'] },
  { id: 'nvidia', name: 'NVIDIA', tier: 1, adapter: 'workday', tenant: 'nvidia', host: 'nvidia.wd5.myworkdayjobs.com', board: 'NVIDIAExternalCareerSite', url: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite', queries: ['safety', 'security', 'privacy', 'audio', 'speech', 'multimodal', 'research intern'] },
  { id: 'meta', name: 'Meta', tier: 1, adapter: 'manual', url: 'https://www.metacareers.com/jobsearch/?q=AI', note: 'Search the official board directly. Automated collection is not available for this source.' },
  { id: 'adobe', name: 'Adobe', tier: 1, adapter: 'workday', tenant: 'adobe', host: 'adobe.wd5.myworkdayjobs.com', board: 'external_experienced', url: 'https://adobe.wd5.myworkdayjobs.com/external_experienced', queries: ['research', 'audio', 'multimodal', 'AI safety', 'privacy'] },
  { id: 'qualcomm', name: 'Qualcomm', tier: 1, adapter: 'manual', url: 'https://careers.qualcomm.com/careers', note: 'Official careers search requires an interactive visit. Check US research and internship roles here.' },
  { id: 'openai', name: 'OpenAI', tier: 2, adapter: 'ashby', board: 'openai', url: 'https://openai.com/careers/search/' },
  { id: 'anthropic', name: 'Anthropic', tier: 2, adapter: 'greenhouse', board: 'anthropic', url: 'https://www.anthropic.com/careers/jobs' },
  { id: 'xai', name: 'xAI', tier: 2, adapter: 'greenhouse', board: 'xai', url: 'https://x.ai/careers' },
  { id: 'cohere', name: 'Cohere', tier: 2, adapter: 'ashby', board: 'cohere', url: 'https://jobs.ashbyhq.com/cohere' },
  { id: 'mistral', name: 'Mistral AI', tier: 2, adapter: 'ashby', board: 'mistral.ai', url: 'https://jobs.ashbyhq.com/mistral.ai' },
  { id: 'dolby', name: 'Dolby', tier: 3, adapter: 'dolby', url: 'https://careers.dolby.com/search/', note: 'US roles from the official Dolby careers board.' },
  { id: 'elevenlabs', name: 'ElevenLabs', tier: 3, adapter: 'ashby', board: 'elevenlabs', url: 'https://jobs.ashbyhq.com/elevenlabs' },
  { id: 'suno', name: 'Suno', tier: 3, adapter: 'ashby', board: 'suno', url: 'https://jobs.ashbyhq.com/suno' },
  { id: 'hume', name: 'Hume AI', tier: 3, adapter: 'ashby', board: 'hume-ai', url: 'https://jobs.ashbyhq.com/hume-ai' },
  { id: 'sesame', name: 'Sesame', tier: 3, adapter: 'ashby', board: 'sesame', url: 'https://jobs.ashbyhq.com/sesame' },
  { id: 'scale', name: 'Scale AI', tier: 3, adapter: 'greenhouse', board: 'scaleai', url: 'https://www.scale.com/careers' },
  { id: 'brave', name: 'Brave', tier: 3, adapter: 'greenhouse', board: 'brave', url: 'https://brave.com/careers/' },
];
